In [1]:

%pip install pandas numpy spacy matplotlib plotly scikit-learn beautifulsoup4 nltk fastopic optuna optuna-dashboard

Requirement already satisfied: pandas in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (2.3.4)
Requirement already satisfied: spacy in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (3.8.7)
Requirement already satisfied: matplotlib in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (3.10.7)
Requirement already satisfied: plotly in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (6.3.1)
Requirement already satisfied: scikit-learn in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (1.7.2)
Requirement already satisfied: beautifulsoup4 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (4.14.2)
Requirement already satisfied: nltk in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (3.9.2)
Requirement already satisfied: fastopic in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (1.0.1)
Requirement already satisfied: optuna in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (4.6.0)
Requirement already satisfied: optuna-dashboard in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (0.20.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (0.20.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.10.5)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: colorama in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (14.2.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (7.4.1)
Requirement already satisfied: wrapt in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from plotly) (2.9.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from scikit-learn) (1.16.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: regex>=2021.8.3 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from nltk) (2025.10.23)
Requirement already satisfied: topmost>=1.0.2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from fastopic) (1.0.2)
Requirement already satisfied: alembic>=1.5.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from optuna) (1.17.2)
Requirement already satisfied: colorlog in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from optuna) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from optuna) (2.0.44)
Requirement already satisfied: PyYAML in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from optuna) (6.0.3)
Requirement already satisfied: bottle>=0.13.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from optuna-dashboard) (0.13.4)
Requirement already satisfied: Mako in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: marisa-trie>=1.1.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.3.1)
Requirement already satisfied: six>=1.5 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: greenlet>=1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: sentence-transformers>=3.4.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from topmost>=1.0.2->fastopic) (5.1.1)
Requirement already satisfied: torchvision>=0.21.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from topmost>=1.0.2->fastopic) (0.24.0)
Requirement already satisfied: gensim>=4.3.3 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from topmost>=1.0.2->fastopic) (4.4.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (4.57.1)
Requirement already satisfied: torch>=1.11.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (2.9.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (0.35.3)
Requirement already satisfied: filelock in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (3.20.0)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (0.6.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (2025.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from torch>=1.11.0->sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from torch>=1.11.0->sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (3.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from jinja2->spacy) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:

import random
import re
import time

import matplotlib.pyplot as plt
import numpy as np
import optuna
import pandas as pd
from fastopic import FASTopic
from gensim.corpora import Dictionary
from gensim.models import CoherenceModel
from wordcloud import WordCloud

## FASTopic

In [3]:
# Carga de datos
test = pd.read_csv("data/research-articles/test.csv")
train = pd.read_csv("data/research-articles/train.csv")

display(test.head())
display(train.head())

,ID,TITLE,ABSTRACT
0,20973,Closed-form Marginal Likelihood in Gamma-Poiss...,We present novel understandings of the Gamma...
1,20974,Laboratory mid-IR spectra of equilibrated and ...,Meteorites contain minerals from Solar Syste...
2,20975,Case For Static AMSDU Aggregation in WLANs,Frame aggregation is a mechanism by which mu...
3,20976,The $Gaia$-ESO Survey: the inner disk intermed...,Milky Way open clusters are very diverse in ...
4,20977,Witness-Functions versus Interpretation-Functi...,Proving that a cryptographic protocol is cor...

,ID,TITLE,ABSTRACT,Computer Science,Physics,Mathematics,Statistics,Quantitative Biology,Quantitative Finance
0,1,Reconstructing Subject-Specific Effect Maps,Predictive models allow subject-specific inf...,1,0,0,0,0,0
1,2,Rotation Invariance Neural Network,Rotation invariance and translation invarian...,1,0,0,0,0,0
2,3,Spherical polyharmonics and Poisson kernels fo...,We introduce and develop the notion of spher...,0,0,1,0,0,0
3,4,A finite element approximation for the stochas...,The stochastic Landau--Lifshitz--Gilbert (LL...,0,0,1,0,0,0
4,5,Comparative study of Discrete Wavelet Transfor...,Fourier-transform infra-red (FTIR) spectra o...,1,0,0,1,0,0

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20972 entries, 0 to 20971
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    20972 non-null  int64
 1   TITLE                 20972 non-null  object
 2   ABSTRACT              20972 non-null  object
 3   Computer Science      20972 non-null  int64
 4   Physics               20972 non-null  int64
 5   Mathematics           20972 non-null  int64
 6   Statistics            20972 non-null  int64
 7   Quantitative Biology  20972 non-null  int64
 8   Quantitative Finance  20972 non-null  int64
dtypes: int64(7), object(2)
memory usage: 1.4+ MB

In [5]:
train.dtypes

ID                       int64
TITLE                   object
ABSTRACT                object
Computer Science         int64
Physics                  int64
Mathematics              int64
Statistics               int64
Quantitative Biology     int64
Quantitative Finance     int64
dtype: object

In [6]:
train_small = train.sample(n=10, random_state=42)
documents = list(train_small.ABSTRACT.values)  # utilizaremos solo la columan Abstract como los documentos
print(documents[0])  # como ejemplo imprimimos el primer documento

  Layer normalization is a recently introduced technique for normalizing the
activities of neurons in deep neural networks to improve the training speed and
stability. In this paper, we introduce a new layer normalization technique
called Dynamic Layer Normalization (DLN) for adaptive neural acoustic modeling
in speech recognition. By dynamically generating the scaling and shifting
parameters in layer normalization, DLN adapts neural acoustic models to the
acoustic variability arising from various factors such as speakers, channel
noises, and environments. Unlike other adaptive acoustic models, our proposed
approach does not require additional adaptation data or speaker information
such as i-vectors. Moreover, the model size is fixed as it dynamically
generates adaptation parameters. We apply our proposed DLN to deep
bidirectional LSTM acoustic models and evaluate them on two benchmark datasets
for large vocabulary ASR experiments: WSJ and TED-LIUM release 2. The
experimental results show that our DLN improves neural acoustic models in terms
of transcription accuracy by dynamically adapting to various speakers and
environments.

In [7]:
clean_text = documents
tokenized_texts = [doc.split() for doc in clean_text]
print(tokenized_texts[0])
dictionary = Dictionary(tokenized_texts)
dictionary.filter_extremes(no_below=5, no_above=0.8)

['Layer', 'normalization', 'is', 'a', 'recently', 'introduced', 'technique', 'for', 'normalizing', 'the', 'activities', 'of', 'neurons', 'in', 'deep', 'neural', 'networks', 'to', 'improve', 'the', 'training', 'speed', 'and', 'stability.', 'In', 'this', 'paper,', 'we', 'introduce', 'a', 'new', 'layer', 'normalization', 'technique', 'called', 'Dynamic', 'Layer', 'Normalization', '(DLN)', 'for', 'adaptive', 'neural', 'acoustic', 'modeling', 'in', 'speech', 'recognition.', 'By', 'dynamically', 'generating', 'the', 'scaling', 'and', 'shifting', 'parameters', 'in', 'layer', 'normalization,', 'DLN', 'adapts', 'neural', 'acoustic', 'models', 'to', 'the', 'acoustic', 'variability', 'arising', 'from', 'various', 'factors', 'such', 'as', 'speakers,', 'channel', 'noises,', 'and', 'environments.', 'Unlike', 'other', 'adaptive', 'acoustic', 'models,', 'our', 'proposed', 'approach', 'does', 'not', 'require', 'additional', 'adaptation', 'data', 'or', 'speaker', 'information', 'such', 'as', 'i-vectors.', 'Moreover,', 'the', 'model', 'size', 'is', 'fixed', 'as', 'it', 'dynamically', 'generates', 'adaptation', 'parameters.', 'We', 'apply', 'our', 'proposed', 'DLN', 'to', 'deep', 'bidirectional', 'LSTM', 'acoustic', 'models', 'and', 'evaluate', 'them', 'on', 'two', 'benchmark', 'datasets', 'for', 'large', 'vocabulary', 'ASR', 'experiments:', 'WSJ', 'and', 'TED-LIUM', 'release', '2.', 'The', 'experimental', 'results', 'show', 'that', 'our', 'DLN', 'improves', 'neural', 'acoustic', 'models', 'in', 'terms', 'of', 'transcription', 'accuracy', 'by', 'dynamically', 'adapting', 'to', 'various', 'speakers', 'and', 'environments.']

In [8]:
def coherence_from_topics(topic_words, tokenized_texts, dictionary):
    if not topic_words:
        return -1e6
    try:
        cm = CoherenceModel(topics=topic_words, texts=tokenized_texts, dictionary=dictionary, coherence='c_v')
        return float(cm.get_coherence())
    except Exception as e:
        print("Error coherence:", e)
        return -1e6

In [9]:
def get_top_words(model, num_top_words=10):
    if num_top_words is None:
        num_top_words = num_top_words
    return model.get_top_words(num_top_words)

In [13]:
def objective(trial):
    """
    Construye un FASTopic con los hiperparámetros sugeridos, entrena (fit_transform)
    y devuelve coherencia c_v (a maximizar).
    """
    # Hiperparámetros a buscar
    n_topics = trial.suggest_int("num_topics", 10, 80)  # rango típico
    DT_alpha = trial.suggest_categorical("DT_alpha", [1.0, 5.0, 10.0, 15.0])
    normalize_embeddings = trial.suggest_categorical("normalize_embeddings", [True, False])
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-3, 1e-1)
    epochs = trial.suggest_int("epochs", 20, 200)

    # build model (constructor flexible según versión)
    try:
        # FASTopic puede aceptar: FASTopic(num_topics, preprocess=..., doc_embed_model=..., normalize_embeddings=...)
        # Aquí usamos constructor con num_topics y algunos flags; si tu versión tiene firma distinta, se adapta por try/except
        model = FASTopic(num_topics=n_topics,
                         normalize_embeddings=normalize_embeddings,
                         DT_alpha=DT_alpha,
                         verbose=False)
    except TypeError:
        # fallback: construir sin algunos argumentos
        model = FASTopic(num_topics=n_topics, verbose=False)

    # Entrenar (fit_transform devuelve top_words y doc_topic_dist según README)

    t0 = time.time()
    top_words_out, doc_topic_dist = model.fit_transform(clean_text, learning_rate=learning_rate, epochs=epochs)
    elapsed = time.time() - t0

    if len(top_words_out) == 0:
        trial.set_user_attr("n_topics_found", 0)
        return -1e6

    topics_for_gensim = get_top_words(model)
    print("Top words found:", topics_for_gensim)

    # calcular coherencia c_v
    coh = coherence_from_topics(topics_for_gensim, tokenized_texts, dictionary)

    # guardar attrs útiles
    trial.set_user_attr("elapsed_s", elapsed)
    trial.set_user_attr("n_topics_found", len(topics_for_gensim))

    return float(coh)

In [14]:
RANDOM_SEED = 42
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
def run_optuna_fastopic(n_trials=20):
    sampler = optuna.samplers.TPESampler(seed=RANDOM_SEED)
    study = optuna.create_study(direction="maximize", sampler=sampler)
    print("Iniciando Optuna para FASTopic. n_trials =", n_trials)
    study.optimize(objective, n_trials=n_trials)
    print("Mejor coherencia:", study.best_value)
    print("Mejores hiperparámetros:", study.best_params)
    return study

In [15]:
study = run_optuna_fastopic(n_trials=20)

[I 2025-12-05 19:06:30,840] A new study created in memory with name: no-name-eb22283a-cc97-49a1-9fc8-20e091c70fa2
C:\Users\zeldan\AppData\Local\Temp\ipykernel_12764\3245100855.py:10: FutureWarning:

suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.

Iniciando Optuna para FASTopic. n_trials = 20

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 3988.12it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 6651.29it/s]
C:\Users\zeldan\anaconda3\envs\tfg-topics2\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning:

The parameter 'token_pattern' will not be used since 'tokenizer' is not None'

Training FASTopic: 100%|██████████| 128/128 [00:14<00:00,  9.07it/s]
[I 2025-12-05 19:06:46,977] Trial 0 finished with value: -1000000.0 and parameters: {'num_topics': 36, 'DT_alpha': 1.0, 'normalize_embeddings': True, 'learning_rate': 0.05399484409787434, 'epochs': 128}. Best is trial 0 with value: -1000000.0.

Top words found: ['popular algorithmic modularity greedy quantitative performance clear counting insight states', 'cases applications linear orders author classical unique suggestion yangian form', 'proposed approach limit improve large adaptive sparsity achieved based modularity', 'gravitational conjectural identification result algebraic yau correspondence unable twisted formulation', 'model new data require generating based time rewards optimal reward', 'code nonlinear pulsedyn non accessible morse fermi body specialists toda', 'terms perturbation explicitly dual paper infty duality supersymmetric large presentation', 'log include pettie round coloring lll currently enlightening checkable essentially', 'degree bounded arxiv improvement rounds log distributed best bound include', 'adaptive deep vectors called variability information benchmark networks adapts recognition', 'acoustic dynamically models layer dln normalization neural technique environments adaptation', 'non pulsedyn nonlinear code lennard integrable fermi specialists pasta tsingou', 'time study numerical field computing question epsilon reward rewards optimal', 'results introduce obtained provides processes prove making known time question', 'susceptibility adaptive improved special thouless matching mean reduced network diagonal', 'time rewards reward optimal epsilon horizon infinite robot stochastic generated', 'mathbf theorem polynomial carleson bounded maximal truncations multidimensional define continuous', 'sphere question authors peron long bochner type positive definite characterisation', 'rewards optimal reward stochastic infinite robot horizon epsilon paths generated', 'maximization insight greedy algorithmic modularity sparsity achieved popular apart level', 'rewards optimal reward stochastic infinite robot horizon epsilon paths generated', 'deep adaptive accuracy wsj lstm vocabulary experiments recently noises speech', 'sphere question follows covariances obstacle schoenberg line geotemporal position definite', 'algebra theory operators koszul omega shown branes background supergravity presented', 'problems graph node complexity problem arbitrary lower step graphs robot', 'non nonlinear pulsedyn code lennard jones soliton ulam systems integrable', 'rewards reward optimal stochastic robot infinite epsilon horizon consider routing', 'propagation method based achieved sparsity formulate random anderson adaptive susceptibility', 'sphere question functions earth survey cross extending related guella positive', 'susceptibility adaptive improved markov computation constructed equation palmer ordinary robust', 'log coloring round pettie lll chung sqrt lcl randomized rounds', 'graphs algorithm algorithms number local known improvement bound distributed best', 'non nonlinear pulsedyn code jones lennard soliton ulam systems integrable', 'classification missing clustering outliers bayesian mixture model introduction latent variables', 'modelling paper classification mixture outliers clustering bayesian missing supervised adopted', 'fixed mathbb kernel zygmund standard lies operator extends let infty']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 4980.18it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 4998.57it/s]
Training FASTopic: 100%|██████████| 114/114 [00:02<00:00, 39.43it/s]
[I 2025-12-05 19:06:51,613] Trial 1 finished with value: -1000000.0 and parameters: {'num_topics': 60, 'DT_alpha': 5.0, 'normalize_embeddings': False, 'learning_rate': 0.0040596116104843075, 'epochs': 114}. Best is trial 0 with value: -1000000.0.

Top words found: ['let maximal multidimensional modulating kernel lies phases standard continuous operator', 'apply information asr datasets vectors networks improves lium release lstm', 'result threefolds classical variable holds quantized identification suggestion coupling formulation', 'branes presented shown perturbation supergravity explicitly omega supersymmetric background dual', 'time question study goal visiting path general asks modeled accumulated', 'sphere guella cross spheres positive long follows authors type goes', 'greedy modularity popular provides insight approach maximization algorithmic limit failure', 'latent approximation gives inference adopted missing bayesian variational values processed', 'performance counting rapid better sparsity apart achieved quantitative level continues', 'sphere lines products berg earth long guella extending motivation covariances', 'compute maximizes disappear collection edges strategies optimization propose total given', 'algorithms algorithmic number maximization local approach insight modularity algorithm graphs', 'environments parameters experimental adaptation deep scaling introduced stability evaluate channel', 'popular insight algorithmic maximization greedy approach proposed modularity community clear', 'belief ordinary robust inverse diagonal mean concept special combining computation', 'chang lower problem labeling significant step arbitrary complexity include essentially', 'algebra koszul theory operators omega background supergravity shown limit presented', 'routing infinite generated epsilon expected finite paths nodes stochastic consider', 'operation identification cft stack quantization unique presentation threefolds yau geometry', 'missing developed sensitivity introduction variables learning scale processed data variational', 'deep speakers parameters environments adaptation neurons vocabulary channel dynamic speaker', 'mathsf run sped ideas recent solved brandt enlightening providing solving', 'round pettie coloring lll lcl randomized sqrt rounds known chung', 'mathbf mathbb carleson polynomial theorem fixed bounded degree operator infty', 'mixture clustering focuses handle having bayesian missing treatment normal possibility', 'results numerical known making non body prove provides models introduce', 'susceptibility propagation method new based adaptive field proposed problems linear', 'specialists nonlinear fermi propagation ulam pasta field jones integrable morse', 'chung sqrt best bound improvement coloring randomized rounds chang lll', 'node graph stochastic horizon consider complexity step lower problem arbitrary', 'scale values distributions allow missing introduction variables adopted supervised sensitivity', 'phenomenon interface open transparency particle black decay single solve excitation', 'matching random reduced combining approaches formulate inverse computation diagonal ordinary', 'log degree graphs algorithm problems bounded number local lll coloring', 'transparency free decay useful literature collision chain scientifically parameter state', 'collects strategy memory probability establish existing objectives unit optimization encode', 'numerical time sphere study modelling applications author results menegatto weather', 'duality dual orders applications gravitational explicitly author conjectural cft holds', 'gravitational orders supersymmetric duality background supergravity cases author dual applications', 'processes computing tsingou body dynamics toda lennard morse accessible soliton', 'ease typically understood mechanism clear implementation continues metastable offer estimating', 'bounded degree continuous infty multidimensional truncations standard lies operator maximal', 'dimension students chains recover quasi simulations equipartitioned potentials easy excitation', 'quasi anticipate easy localized students recurrence benchmarking useful accurate examine', 'fields concept palmer anderson network approaches thouless computation mean approximate', 'generates variability speech adapts arising benchmark training networks additional ted', 'acoustic models dln neural normalization layer dynamically proposed adaptive approach', 'generating require new dynamically adaptation parameters environments deep speakers recognition', 'cases linear equation ising improved constructed structures approximate response thouless', 'states update estimating presumably metastable rule quantitative forming communication performance', 'yangian constants loop correspondence dimensional algebraic form double quantum calabi', 'code pulsedyn non nonlinear jones integrable systems lennard soliton ulam', 'technique speakers adaptation deep environments parameters improve dynamically normalization layer', 'bounds average objectives locations maximize potential computational according traveling discrete', 'survey sphere functions geostatistical peron covariances berg goes guella characterisation', 'rewards reward optimal problems robot epsilon model infinite horizon new', 'distributed showed include revelation randomized currently defective upper frugal progress', 'question sphere bochner study prediction case line weather time follows', 'extends obtained zygmund define kernel phases truncations modulating operator maximal', 'classification outliers model based bayesian clustering mixture missing data method']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 2218.97it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 4997.98it/s]
Training FASTopic: 100%|██████████| 56/56 [00:02<00:00, 22.08it/s]
[I 2025-12-05 19:06:55,961] Trial 2 finished with value: -1000000.0 and parameters: {'num_topics': 40, 'DT_alpha': 5.0, 'normalize_embeddings': False, 'learning_rate': 0.037183641805732096, 'epochs': 56}. Best is trial 0 with value: -1000000.0.

Top words found: ['susceptibility ordinary structures mean inverse anderson special thouless random approximate', 'bounded degree brandt variant relaxed currently solving checkable providing significant', 'operators perturbation supersymmetric explicitly infty dual branes quantized holds yau', 'problems based appear maximize disappear propose visiting collected locations distance', 'pulsedyn toda jones tsingou body soliton ulam fermi dynamics lennard', 'fixed theorem mathbf modulating extends maximal carleson mathbb zygmund truncations', 'models recognition fixed adapts stability lium speech adapting datasets unlike', 'approach modularity algorithmic maximization popular greedy algorithms apart provides implementation', 'polynomial carleson mathbb mathbf theorem define continuous let operator lies', 'peron products raised geotemporal weather sphere cross motivation definite multiple', 'results non nonlinear code systems numerical models model computing time', 'missing method possibility distributions classification approximation supervised treatment focuses developed', 'algorithm graphs problems complexity lower node graph arbitrary problem step', 'pettie round lll chung lcl randomized sqrt improvement bound include', 'insight limit persistently states sparsity forming better typically achieved ease', 'proposed results adaptive new approach improve models introduce require model', 'insight metastable quantitative clear issue risk performance understood rapid fails', 'peron raised products cross motivation weather definite geotemporal multiple guella', 'rewards optimal epsilon stochastic horizon infinite generated reward robot paths', 'acoustic dln normalization neural layer dynamically adaptation speakers technique deep', 'time model limit processes generating require question dynamically computing given', 'long menegatto authors survey earth schoenberg covariances goes characterisation bochner', 'omega operators theory supersymmetric perturbation explicitly large branes terms dual', 'infty obtained operators kernel standard multidimensional phases truncations zygmund maximal', 'data models fixed model information unlike stability adapts recognition speech', 'model classification data clustering outliers bayesian mixture paper missing modelling', 'time sphere study question numerical author applications related modelling case', 'reward robot graph node routing consider expected finite paths step', 'propagation method cases field linear susceptibility based network approaches fields', 'applications author operators unique linear calabi analog presentation cft cases', 'values gives variables variational sensitivity normal introduction learning latent inference', 'log coloring degree bounded distributed rounds lll conjecture automatically run', 'morse specialists obtained integrable propagation quasi allows simulations ensure achieve', 'local number known algorithms results making prove revelation arxiv solved', 'algebra theory koszul presented background shown supergravity branes gravitational orders', 'nodes existing path objectives encode total strategy formalizing strategies memory', 'models parameters large environments terms introduce dynamically require generating paper', 'specialists morse propagation integrable ensure black simulations allows equipartitioned equilibrium', 'propagation integrable specialists morse accessible pasta field transparency iii source', 'susceptibility computation combining improved equation belief constructed markov matching formulate']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 3330.40it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 10005.50it/s]
Training FASTopic: 100%|██████████| 166/166 [00:31<00:00,  5.34it/s]
[I 2025-12-05 19:07:28,824] Trial 3 finished with value: -1000000.0 and parameters: {'num_topics': 46, 'DT_alpha': 10.0, 'normalize_embeddings': False, 'learning_rate': 0.08536189862866832, 'epochs': 166}. Best is trial 0 with value: -1000000.0.

Top words found: ['graphs algorithm local number algorithms step proposed lower modularity greedy', 'mixture outliers inference allow having data treatment distributions latent restrictive', 'operators supersymmetric gravitational double form yangian operation result formulated yau', 'modularity insight maximization greedy popular algorithms failure presumably counting mechanism', 'bounded carleson mathbb obtained modulating kernel lies zygmund multidimensional fixed', 'ordinary mean approximate thouless structures constructed equation computation concept adaptive', 'robot nodes finite problem takes total maximizes memory traveling propose', 'pulsedyn nonlinear code tsingou soliton lennard dynamics morse accessible fermi', 'chang recent run revelation upper enlightening relaxed progress currently algorithm', 'mixture outliers model latent treatment sensitivity focuses inference having allow', 'information accuracy speaker unlike neurons training noises transcription wsj generates', 'cases inverse robust belief markov reduced matching network linear susceptibility', 'collected path maximize collects step local number algorithm strategies average', 'modelling bochner guella menegatto geotemporal functions similarly follows line covariances', 'rewards optimal reward stochastic horizon epsilon routing consider infinite collected', 'time study numerical type position geostatistical answered related extending case', 'results provides prove numerical transparency study time geostatistical making position', 'model method based field dynamically propagation new data computing theory', 'characterisation lines berg spheres products raised porcu positive authors prediction', 'sphere extensions obstacle definite long multiple weather earth survey motivation', 'modularity insight maximization greedy popular algorithms proposed mechanism level failure', 'pasta body systems specialists ulam integrable jones processes equilibrium parameter', 'coloring chung rounds lemma frugal significant currently solving defective list', 'susceptibility linear approaches fields palmer special improved ising diagonal cases', 'time infinite paths generated limit model require encode potential given', 'models dynamically fixed adaptive proposed speakers data environments new improve', 'log bounded making conjectured labeling automatically brandt ideas checkable lower', 'introduce model computing theory single setting known time field based', 'improvement include conjecture sped variant providing classic solved problem bounded', 'popular greedy maximization modularity insight algorithms achieved better sparsity metastable', 'problems degree node graph complexity arbitrary known question generating omega', 'algorithmic approach persistently offer rapid issue implementation ease quantitative proposed', 'dln terms parameters adaptation deep technique paper results improves variability', 'dual certain explicit unique algebraic suggestion formulation suggested cft identification', 'acoustic neural normalization layer environments adapting experimental experiments speakers introduced', 'propagation proposed new formulate anderson combining response dynamically model method', 'dynamical anticipate box simulations useful ensure easy localized literature chains', 'propagation toda distribute state dimension free solve achieve equipartitioned file', 'classification clustering bayesian missing data model outliers variables handle mixture', 'pettie lll round randomized lcl sqrt bound distributed best arxiv', 'expected probability disappear objectives general accumulated goal strategy optimization require', 'omega orders author dimensional conjectural quantization stack correspondence analog quantized', 'algebra koszul theory branes supergravity shown background presented limit explicitly', 'study establish average disappears computational bounds strategies formalizing edges compute', 'mathbf polynomial theorem standard let continuous truncations maximal operator define', 'non paper large examine chain scientifically black mathsf linear terms']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 2497.20it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 4998.57it/s]
Training FASTopic: 100%|██████████| 66/66 [00:04<00:00, 13.46it/s]
[I 2025-12-05 19:07:35,453] Trial 4 finished with value: -1000000.0 and parameters: {'num_topics': 31, 'DT_alpha': 5.0, 'normalize_embeddings': True, 'learning_rate': 0.06586289317583113, 'epochs': 66}. Best is trial 0 with value: -1000000.0.

Top words found: ['sqrt local rounds known locally ideas list showed brandt significant', 'insight popular maximization algorithmic greedy forming update understood risk typically', 'adaptation technique dln adapts neurons normalizing unlike bidirectional activities lium', 'new based collects computational strategies path strategy collection given accumulated', 'rewards reward optimal epsilon horizon infinite stochastic robot consider time', 'modularity ease metastable achieved continues rapid apart counting performance communication', 'menegatto porcu similarly lines extensions obstacle earth functions guella motivation', 'acoustic normalization neural layer dynamically dln speakers parameters deep improve', 'susceptibility combining reduced special diagonal concept structures response formulate computation', 'results prove known making broadly recover anticipate recurrence dynamical free', 'bounded mathbb carleson obtained mathbf theorem polynomial maximal kernel truncations', 'non numerical allows program state scientifically box equilibrium literature interface', 'model results proposed paper study models generating introduce require time', 'theory background omega perturbation gravitational conjectural enumerative loop determine explicit', 'degree bounded chang include arxiv classic defective progress essentially solved', 'question time sphere prediction products line survey long spheres raised', 'algebra koszul shown presented branes supergravity theory orders duality explicitly', 'nodes routing finite expected generated paths memory maximize goal disappear', 'applications multiple geotemporal extending follows geostatistical bochner berg peron goes', 'operators large fixed terms infty coupling holds stack yangian quantized', 'log coloring round lll lcl chung randomized bound improvement best', 'polynomial theorem mathbf multidimensional let define standard continuous operator modulating', 'propagation field code benchmarking iii pulsedyn simulations chains open ensure', 'classification missing clustering bayesian mixture outliers processed gives treatment values', 'dual limit author quantum certain unique classical calabi result ads', 'data classification outliers bayesian mixture missing clustering modelling method approximation', 'nonlinear pulsedyn code systems lennard integrable pasta accessible ulam specialists', 'problems graphs algorithm pettie complexity graph node lower problem arbitrary', 'algorithms approach number algorithm fails mechanism level states presumably estimating', 'models adaptive environments vectors transcription wsj ted arising speaker release', 'method adaptive linear based cases fields robust belief new constructed']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 3332.25it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 5003.34it/s]
Training FASTopic: 100%|██████████| 181/181 [00:30<00:00,  5.87it/s]
[I 2025-12-05 19:08:08,110] Trial 5 finished with value: -1000000.0 and parameters: {'num_topics': 57, 'DT_alpha': 10.0, 'normalize_embeddings': True, 'learning_rate': 0.0756829206016762, 'epochs': 181}. Best is trial 0 with value: -1000000.0.

Top words found: ['neural shifting bidirectional accuracy recently stability speech called activities experimental', 'results definite positive long peron related answered earth time sphere', 'operators koszul branes shown perturbation unique infty cases linear enumerative', 'time problems study numerical computing results sqrt propagation scientifically distributed', 'degree bounded ideas vertex significant omega results known making automatically', 'algorithmic provides limit understood offer persistently community level insight maximization', 'susceptibility ising anderson combining robust fields matching constructed random reduced', 'propagation equation markov approaches computation susceptibility random reduced special constructed', 'node graph step lower algorithm complexity problem arbitrary graphs log', 'geostatistical extensions functions spheres berg menegatto follows sphere covariances position', 'method based adaptive new belief field proposed susceptibility constructed propagation', 'expected routing consider generated nodes finite horizon processes collects limit', 'model approach data based method results paper classification proposed outliers', 'treatment possibility developed latent allow focuses having paper bayesian processed', 'linear cases unique determine applications enumerative operators susceptibility koszul branes', 'author calabi constants formulation quantum dimensional yau formulated ads quantization', 'modularity greedy popular maximization insight algorithms forming apart quantitative better', 'bayesian classification outliers variables distributions inference missing modelling variational clustering', 'graphs achieved typically algorithm results algorithms step node complexity arbitrary', 'terms large paper explicit presentation cft yangian form quantized double', 'carleson continuous lies zygmund truncations maximal multidimensional mathbf theorem polynomial', 'asks maximize computational strategy formalizing path optimization process total graph', 'fixed evaluate variability introduced additional experiments adapting speed apply ted', 'number local algorithms results improve providing classic graphs algorithm proposed', 'problems ordinary approximate thouless inverse network diagonal concept mean susceptibility', 'classification model mixture clustering missing outliers based method handle values', 'known checkable prove making progress variant relaxed defective lemma run', 'pulsedyn tsingou morse ulam soliton toda nonlinear code dimension fermi', 'greedy modularity maximization popular insight algorithms apart detection risk quantitative', 'rewards reward optimal infinite stochastic epsilon horizon according distance robot', 'sphere applications modelling motivation geotemporal covariances products bochner position multiple', 'collected bounds unit general given visiting propose discrete traveling compute', 'case schoenberg sphere authors obstacle porcu characterisation line similarly cross', 'mathbb polynomial theorem kernel standard define phases modulating mathbf extends', 'non students box rich processes theory limit algebra checked gravitational', 'proposed adaptive lium factors vocabulary improves information datasets size adapts', 'localized decay equilibrium distribute quasi free collision broadly excitation state', 'acoustic models dln normalization layer environments technique introduce paper large', 'results propagation introduce models program file dynamical black equipartitioned anticipate', 'dynamically require generating new improve model adaptive proposed size robot', 'mathbf bounded obtained theorem operator let extends modulating multidimensional polynomial', 'conjectured automatically upper recent frugal sped solved currently mathsf revelation', 'algebra theory omega supergravity gravitational dual duality background orders supersymmetric', 'survey extending guella prediction raised question sphere modelling motivation covariances', 'formulate response palmer improved structures special reduced random susceptibility constructed', 'presented background algebra explicitly supergravity suggested suggestion analog identification threefolds', 'sphere applications modelling motivation geotemporal covariances products bochner position multiple', 'strategies provide goal potential locations question takes disappear memory rewards', 'robot model paths based disappears edges appear encode probability maximizes', 'code nonlinear numerical body lennard specialists pasta systems integrable dynamics', 'popular modularity insight greedy maximization algorithms proposed ease mechanism states', 'log round lll coloring pettie algorithm graphs chung randomized lcl', 'classification bayesian outliers missing clustering mixture inference variables modelling sensitivity', 'problems sqrt best include rounds distributed labeling conjecture log coloring', 'infty operators fixed result determine enumerative mathbf theorem extends carleson', 'adaptation deep parameters speakers wsj dynamic arising recognition vectors benchmark', 'benchmarking potentials easy accurate making chain recurrence interface ensure designed']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 5001.55it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 5002.15it/s]
Training FASTopic: 100%|██████████| 170/170 [00:05<00:00, 31.78it/s]
[I 2025-12-05 19:08:15,427] Trial 6 finished with value: -1000000.0 and parameters: {'num_topics': 52, 'DT_alpha': 1.0, 'normalize_embeddings': False, 'learning_rate': 0.003488976654890368, 'epochs': 170}. Best is trial 0 with value: -1000000.0.

Top words found: ['related obstacle menegatto similarly peron products extensions geotemporal functions position', 'pulsedyn nonlinear code non accessible dynamics morse lennard specialists tsingou', 'algebra theory omega koszul operators non arxiv branes limit presented', 'markov approximate anderson approaches random concept fields combining palmer diagonal', 'path appear strategies total optimization disappear collection objectives process existing', 'mixture values variational scale treatment possibility sensitivity developed learning processed', 'multidimensional operator zygmund standard define kernel modulating lies let maximal', 'classification model data clustering missing outliers bayesian paper based mixture', 'benchmark speakers transcription normalizing networks additional channel datasets vectors experimental', 'mixture treatment normal processed variational scale latent approximation sensitivity developed', 'approach algorithms algorithmic maximization popular insight modularity greedy limit number', 'known bound include best chang improvement rounds chung distributed randomized', 'ensure rich recurrence distribute useful potentials allows localized program examine', 'setting collision interface equipartitioned single dynamical open equilibrium benchmarking examine', 'results systems fermi pasta numerical jones ulam making prove study', 'modelling positive berg porcu weather guella answered geotemporal menegatto position', 'introduced evaluate unlike benchmark transcription vocabulary recognition activities arising datasets', 'infty operators yau analog determine variable result constants quantum twisted', 'fixed introduce improve speech generates speed size lium stability asr', 'combining concept approximate computation anderson thouless approaches markov equation fields', 'gives handle restrictive modelling focuses inference introduction supervised distributions adopted', 'characterisation covariances bochner line products motivation case positive spheres guella', 'greedy modularity provides insight popular maximization algorithmic fails performance continues', 'forming ease persistently communication implementation level counting clear states failure', 'log pettie round lll coloring lcl sqrt randomized chung distributed', 'speakers parameters deep environments adaptation networks additional transcription improves introduced', 'currently variant checkable classic solving ideas mathsf brandt automatically defective', 'holds quantized classical stack cft form formulation identification certain quantization', 'graph node lower step problem arbitrary complexity routing horizon robot', 'susceptibility method based reduced special matching ordinary formulate belief robust', 'bounded degree solved relaxed providing defective recent progress automatically revelation', 'explicitly gravitational perturbation duality orders supersymmetric dual presented background shown', 'author applications linear cases suggested presentation unable calabi ads conjectural', 'theorem mathbb carleson polynomial mathbf obtained zygmund operator lies multidimensional', 'solve easy decay iii allows transparency students recover box quasi', 'acoustic dynamically normalization neural layer adaptive dln proposed require generating', 'holds quantized classical stack cft threefolds certain formulation yangian form', 'body specialists tsingou integrable morse soliton toda lennard dynamics accessible', 'disappears encode provide distance compute probability bounds maximizes goal discrete', 'graphs algorithm problems complexity number local problem arbitrary lower step', 'mechanism understood typically update detection rule community apart presumably continues', 'speakers parameters datasets recognition lstm training networks vectors factors vocabulary', 'phases extends maximal continuous truncations standard let define modulating kernel', 'proposed ising mean response adaptive network new inverse improved based', 'supergravity background shown presented branes dual supersymmetric orders duality perturbation', 'sphere time study numerical question motivation survey type schoenberg authors', 'models dln layer neural technique adaptation environments normalization large deep', 'infinite generated expected paths finite nodes consider robot stochastic epsilon', 'collected strategies collection takes objectives average maximize locations appear according', 'essentially run conjecture labeling vertex lemma upper sped significant list', 'rewards optimal reward time horizon problems epsilon stochastic robot model', 'field propagation linear cases structures equation diagonal palmer matching random']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 3251.40it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 9984.06it/s]
Training FASTopic: 100%|██████████| 55/55 [00:07<00:00,  7.11it/s]
[I 2025-12-05 19:08:24,909] Trial 7 finished with value: -1000000.0 and parameters: {'num_topics': 35, 'DT_alpha': 15.0, 'normalize_embeddings': False, 'learning_rate': 0.03503398491158688, 'epochs': 55}. Best is trial 0 with value: -1000000.0.

Top words found: ['mathbb mathbf operator phases extends let zygmund define continuous modulating', 'classification missing outliers bayesian method mixture clustering sensitivity handle variables', 'propagation field collision phenomenon dimension localized rich recover distribute potentials', 'time sphere raised multiple characterisation bochner definite porcu authors similarly', 'algorithms number local results algorithm graphs improve approach prove making', 'collects distance accumulated based maximizes disappears visiting objectives average computational', 'problems node step arbitrary lower problem algorithm graph complexity graphs', 'models improve introduce proposed data fixed model results paper new', 'susceptibility method ordinary belief reduced random equation concept ising fields', 'fails mechanism ease metastable rapid issue communication understood failure performance', 'mean approximate response matching special robust markov palmer linear cases', 'operators infty identification formulated certain algebraic form variable analog conjectural', 'model data paper based modelling scale having supervised inference treatment', 'clustering mixture classification bayesian outliers missing processed normal approximation possibility', 'propagation susceptibility proposed problems new combining network computation structures based', 'bounded theorem carleson polynomial degree lies truncations maximal mathbf kernel', 'results nonlinear pulsedyn non specialists jones lennard soliton tsingou fermi', 'algebra shown omega supergravity dual orders duality explicitly cases gravitational', 'counting implementation update states level clear offer sparsity risk typically', 'peron answered line position products weather geotemporal obstacle earth extensions', 'acoustic normalization dln layer dynamically environments deep adaptation speakers parameters', 'approach insight maximization algorithmic popular greedy modularity proposed limit better', 'suggested correspondence threefolds holds calabi yangian dimensional result coupling yau', 'neural technique parameters additional networks speech speaker lstm evaluate activities', 'models time study introduce transparency model achieve students computing anticipate', 'log problems degree coloring lll pettie graphs algorithm bounded lcl', 'round sqrt randomized chung bound best chang distributed rounds improvement', 'essentially variant solved locally frugal currently progress list automatically relaxed', 'apply adapts stability recognition dynamic speed release generates bidirectional shifting', 'algebra theory koszul presented background branes omega perturbation supergravity supersymmetric', 'optimal epsilon robot infinite stochastic routing generated paths nodes modeled', 'code systems accessible toda morse ulam body integrable dynamics pasta', 'fixed obtained carleson theorem polynomial dynamical mathbf relaxed examine equipartitioned', 'case spheres functions geostatistical cross motivation covariances lines schoenberg survey', 'rewards reward horizon time consider finite expected model computing graph']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 3333.57it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 9929.70it/s]
Training FASTopic: 100%|██████████| 176/176 [00:03<00:00, 55.04it/s]
[I 2025-12-05 19:08:29,843] Trial 8 finished with value: -1000000.0 and parameters: {'num_topics': 10, 'DT_alpha': 1.0, 'normalize_embeddings': False, 'learning_rate': 0.0017050539260269294, 'epochs': 176}. Best is trial 0 with value: -1000000.0.

Top words found: ['theorem mathbf carleson mathbb polynomial let extends zygmund multidimensional operator', 'pulsedyn code nonlinear non toda ulam dynamics body systems integrable', 'algebra theory operators koszul branes shown supergravity presented background omega', 'susceptibility ising formulate improved constructed thouless reduced special approximate network', 'log degree bounded pettie coloring round lll local number randomized', 'acoustic models dynamically layer normalization neural dln adaptation technique parameters', 'rewards optimal reward robot infinite horizon epsilon stochastic expected finite', 'missing outliers bayesian clustering mixture classification focuses supervised developed latent', 'insight maximization greedy popular algorithmic modularity algorithms approach communication failure', 'sphere weather earth line spheres positive obstacle authors related extensions']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 3341.28it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 3985.84it/s]
Training FASTopic: 100%|██████████| 105/105 [00:18<00:00,  5.56it/s]
[I 2025-12-05 19:08:50,608] Trial 9 finished with value: -1000000.0 and parameters: {'num_topics': 54, 'DT_alpha': 1.0, 'normalize_embeddings': True, 'learning_rate': 0.059487468132197734, 'epochs': 105}. Best is trial 0 with value: -1000000.0.

Top words found: ['sphere weather long menegatto prediction positive berg type lines definite', 'pulsedyn code nonlinear morse systems fermi tsingou lennard integrable jones', 'rewards reward optimal nodes expected generated paths consider time formalizing', 'sphere long prediction menegatto bochner geotemporal schoenberg position raised cross', 'applications modelling author obstacle question omega explicitly algebra ads classical', 'method susceptibility diagonal matching ordinary thouless concept formulate approximate fields', 'rewards optimal reward question nodes expected generated time paths consider', 'local number chang include rounds prove conjectured solved distributed algorithms', 'log lll coloring round pettie lcl sqrt chung degree distributed', 'classification clustering missing bayesian mixture outliers data handle normal treatment', 'sphere time peron guella geotemporal cross bochner porcu products functions', 'study limit time processes computing question provides obtained numerical greedy', 'mathbf carleson mathbb theorem polynomial standard multidimensional truncations modulating operator', 'susceptibility special improved response combining network constructed ising structures mean', 'numerical obtained provides code nonlinear pulsedyn pasta toda body ulam', 'algebra operators koszul shown supergravity background gravitational omega explicitly constants', 'rewards reward optimal robot epsilon horizon stochastic time finite routing', 'model data based require dynamically generating method new improve missing', 'omega explicitly conjectural constants stack dimensional unique determine calabi analog', 'better ease sparsity failure maximization popular insight modularity greedy algorithmic', 'fixed acoustic adaptation adapting datasets dln neurons adapts lium ted', 'explicitly yau quantum twisted holds loop unable enumerative suggested checked', 'mathbb mathbf theorem carleson polynomial fixed modulating truncations extends kernel', 'rewards optimal reward robot horizon epsilon stochastic time finite routing', 'problems graph node infinite step lower problem arbitrary algorithm graphs', 'theory branes presented perturbation supersymmetric duality orders dual explicitly suggestion', 'graphs algorithm problems randomized complexity improve arbitrary problem lower step', 'acoustic layer dln neural normalization technique deep environments parameters adaptation', 'propagation field inverse random method susceptibility diagonal thouless concept matching', 'making known defective brandt sped ideas progress solving checkable variant', 'non nonlinear code accessible soliton ulam pulsedyn body pasta toda', 'proposed approach adaptive algorithms insight greedy algorithmic popular modularity provides', 'acoustic dln layer improve neural normalization technique dynamically deep environments', 'field known decay equilibrium achieve box students chain systems tsingou', 'define continuous phases let polynomial mathbf carleson theorem mathbb lies', 'classification clustering missing bayesian outliers mixture restrictive distributions handle normal', 'classification clustering missing bayesian mixture outliers data treatment scale learning', 'improvement best bound relaxed locally vertex lemma mathsf run significant', 'algorithms greedy insight algorithmic modularity popular maximization rapid detection community', 'results introduce provides prove algorithms proposed numerical obtained greedy adaptive', 'algorithms greedy algorithmic insight modularity popular maximization detection rapid issue', 'pulsedyn nonlinear code systems fermi tsingou morse integrable lennard jones', 'time question rewards optimal reward nodes expected generated paths consider', 'models speakers acoustic adaptation dln normalization neural layer lstm parameters', 'paper terms large models speakers presented branes duality orders dual', 'explicitly yau quantum twisted holds loop suggested unable checked enumerative', 'bounded degree arxiv infty omega algebra koszul shown background supergravity', 'acoustic layer dln neural normalization technique deep environments parameters adaptation', 'pulsedyn code nonlinear jones morse lennard integrable fermi systems tsingou', 'maximization algorithmic modularity popular insight greedy apart counting rule typically', 'cases linear omega cft double explicitly quantum checked geometry suggested', 'sphere weather long menegatto prediction positive definite lines type schoenberg', 'new dynamically require generating based improve proposed approach model adaptive', 'susceptibility method thouless diagonal matching formulate belief structures improved special']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 3328.81it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 10017.44it/s]
Training FASTopic: 100%|██████████| 122/122 [00:10<00:00, 12.05it/s]
[I 2025-12-05 19:09:02,538] Trial 10 finished with value: -1000000.0 and parameters: {'num_topics': 77, 'DT_alpha': 15.0, 'normalize_embeddings': True, 'learning_rate': 0.012764937047792487, 'epochs': 122}. Best is trial 0 with value: -1000000.0.

Top words found: ['problems essentially vertex run checkable labeling solved recent mathsf showed', 'time question applications author sphere study modelling covariances spheres products', 'recently modeling experiments unlike activities shifting information wsj benchmark improves', 'simulations dimension easy ensure recurrence setting decay broadly potentials iii', 'modeling recently experiments shifting unlike information benchmark activities wsj experimental', 'known making prove improvement include bound upper currently automatically list', 'new adaptive proposed anderson reduced mean markov belief thouless constructed', 'propagation field linear cases susceptibility method approaches structures fields improved', 'popular greedy maximization insight algorithmic modularity ease community persistently implementation', 'markov belief reduced ordinary mean anderson inverse random ising matching', 'bounded degree carleson polynomial mathbb mathbf theorem obtained standard zygmund', 'theorem mathbf mathbb polynomial carleson kernel modulating define let continuous', 'algorithms graphs algorithm local number results better limit provides approach', 'sphere geostatistical authors prediction functions survey lines earth geotemporal porcu', 'problems node graph problem complexity step arbitrary lower graphs algorithm', 'fixed modulating continuous define lies kernel maximal let operator phases', 'formulated classical stack geometry dimensional variable identification loop form result', 'sphere prediction authors geostatistical earth geotemporal porcu long cross lines', 'sphere geostatistical authors prediction similarly lines goes type porcu survey', 'models acoustic neural layer normalization dln adaptation introduce deep environments', 'algebra theory operators koszul supergravity presented background branes shown non', 'presented koszul shown branes background supergravity paper duality dual supersymmetric', 'model data paper based method classification outliers clustering bayesian missing', 'infty operators algebra theory polynomial carleson bounded mathbf mathbb theorem', 'non propagation results theory models introduce prove making model known', 'outliers mixture missing bayesian clustering classification latent adopted possibility focuses', 'rewards optimal reward stochastic horizon infinite robot epsilon paths consider', 'code nonlinear pulsedyn accessible specialists ulam morse jones pasta body', 'acoustic normalization dln layer neural parameters technique environments speakers deep', 'log degree bounded coloring lll round pettie known results improve', 'conjectured classic locally lemma relaxed ideas providing frugal progress significant', 'new generating require dynamically reward epsilon robot optimal rewards infinite', 'code nonlinear pulsedyn jones accessible specialists morse ulam fermi pasta', 'computing processes source transparency distribute dynamical literature excitation accurate obtained', 'greedy popular modularity algorithmic insight maximization implementation ease level rule', 'simulations dimension decay easy iii recurrence potentials parameter ensure setting', 'modeling recently experiments fixed benchmark shifting improves dynamic wsj activities', 'modulating continuous define fixed kernel lies let maximal operator phases', 'dimension simulations decay easy iii recurrence potentials ensure box benchmarking', 'formulated stack dimensional classical geometry loop variable result form identification', 'omega koszul branes background presented shown supergravity theory arxiv algebra', 'outliers mixture missing bayesian clustering classification latent adopted focuses possibility', 'theorem mathbf mathbb polynomial carleson kernel multidimensional operator let maximal', 'stack formulated dimensional geometry variable classical result yau loop explicit', 'method based susceptibility improved fields special equation computation matching inverse', 'outliers mixture missing bayesian clustering classification latent adopted focuses possibility', 'disappear discrete process formalizing compute establish collects distance encode given', 'time model study computing processes question nodes epsilon robot reward', 'sphere porcu similarly functions obstacle type lines goes positive definite', 'results numerical study time question computing processes model provides known', 'koszul shown branes background presented supergravity gravitational theory dual perturbation', 'lll round pettie lcl coloring sqrt chung randomized distributed rounds', 'sphere porcu authors similarly earth prediction cross definite geostatistical lines', 'polynomial carleson mathbb mathbf theorem obtained standard zygmund multidimensional extends', 'discrete disappear compute formalizing process establish encode given distance collects', 'susceptibility method structures formulate approaches robust response equation approximate combining', 'recently modeling introduced benchmark variability unlike speed wsj normalizing experiments', 'greedy popular modularity algorithmic insight maximization ease implementation community level', 'ideas locally providing classic automatically frugal conjectured relaxed enlightening lemma', 'markov belief reduced ordinary anderson mean inverse random ising matching', 'sphere geostatistical prediction authors geotemporal long porcu earth lines goes', 'algorithm graphs complexity number local node graph problem lower step', 'markov belief reduced ordinary mean anderson inverse random ising matching', 'formulated stack classical dimensional variable geometry loop quantum holds identification', 'discrete disappear process compute formalizing establish encode given collects distance', 'rewards optimal reward stochastic horizon robot infinite epsilon consider paths', 'mixture outliers missing latent allow values variational possibility introduction handle', 'popular maximization insight greedy algorithmic modularity ease metastable community persistently', 'paper large terms dln layer acoustic adaptive normalization neural data', 'pettie round lll coloring chung sqrt randomized lcl chang distributed', 'outliers mixture missing bayesian clustering latent variational allow possibility adopted', 'dynamically acoustic proposed neural generating models require results adaptive dln', 'greedy modularity algorithmic popular insight maximization implementation level rule ease', 'dimension simulations decay easy iii recurrence potentials ensure setting parameter', 'pulsedyn nonlinear code dynamics soliton toda integrable ulam body systems', 'approach proposed insight maximization modularity greedy algorithmic popular provides apart', 'classification clustering bayesian missing mixture outliers data method modelling normal']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 3984.33it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 5000.36it/s]
Training FASTopic: 100%|██████████| 122/122 [00:03<00:00, 31.94it/s]
[I 2025-12-05 19:09:08,157] Trial 11 finished with value: -1000000.0 and parameters: {'num_topics': 70, 'DT_alpha': 5.0, 'normalize_embeddings': True, 'learning_rate': 0.007608069116082095, 'epochs': 122}. Best is trial 0 with value: -1000000.0.

Top words found: ['maximization modularity greedy popular insight algorithmic achieved forming ease apart', 'parameter box achieve dimension iii dynamical setting transparency interface free', 'explicitly duality dual supersymmetric shown orders gravitational supergravity presented background', 'carleson theorem mathbf mathbb polynomial lies truncations kernel zygmund continuous', 'infty operators ads formulated unable constants dimensional classical yau geometry', 'propagation susceptibility problems proposed field adaptive new method based linear', 'computational path average visiting accumulated maximize optimization probability compute appear', 'classic checkable run sped progress lemma relaxed automatically conjecture enlightening', 'polynomial mathbb carleson mathbf theorem obtained define let maximal operator', 'sphere characterisation berg products porcu case geostatistical position earth goes', 'information transcription speech dynamic shifting bidirectional neurons vocabulary networks improves', 'approach algorithms algorithm graphs number local proposed results limit algorithmic', 'sphere answered covariances multiple survey positive obstacle bochner lines menegatto', 'time study numerical results question sphere multiple functions guella raised', 'pulsedyn nonlinear dynamics code integrable systems jones morse accessible specialists', 'presented branes koszul background shown supergravity perturbation gravitational omega orders', 'speakers fixed adapts additional vocabulary generates unlike deep experimental shifting', 'omega arxiv background shown supergravity presented branes gravitational orders duality', 'acoustic neural dln normalization dynamically layer large adaptation terms deep', 'paper data bidirectional training asr experiments apply lstm improves introduced', 'horizon infinite optimal epsilon stochastic robot rewards paths expected generated', 'processes computing obtained excitation ensure open black interface designed state', 'model classification data based method paper outliers bayesian clustering mixture', 'algebra theory operators koszul omega non supergravity cases shown background', 'sphere author applications modelling berg line authors extending porcu products', 'round coloring lll chung lcl known sqrt pettie randomized prove', 'node graph complexity problem lower step arbitrary robot optimal routing', 'popular greedy modularity maximization insight algorithmic detection metastable states quantitative', 'variable supersymmetric quantization form yangian twisted identification coupling determine algebraic', 'missing mixture clustering bayesian outliers adopted inference sensitivity normal values', 'missing mixture clustering outliers bayesian scale introduction normal values handle', 'equation mean markov ising approximate palmer ordinary special network robust', 'sphere author applications berg authors characterisation extending type prediction peron', 'pettie randomized distributed sqrt chang include coloring bound improvement rounds', 'missing clustering mixture bayesian outliers processed latent allow variational treatment', 'provides maximization modularity popular insight greedy clear algorithmic issue continues', 'suggested suggestion quantized stack analog algebraic identification presentation result determine', 'missing mixture bayesian clustering outliers distributions supervised inference focuses learning', 'ordinary equation diagonal markov approximate ising network constructed mean palmer', 'nonlinear pulsedyn lennard code fermi jones toda soliton ulam specialists', 'markov equation ising ordinary mean special inverse palmer robust approximate', 'sphere author applications position geostatistical berg authors porcu case type', 'pulsedyn nonlinear systems tsingou integrable soliton body toda accessible dynamics', 'mathbf theorem carleson mathbb polynomial truncations standard zygmund kernel operator', 'maximization modularity greedy popular insight achieved persistently update performance forming', 'parameter program simulations dynamical iii broadly allows box chain transparency', 'wsj arising called variability vectors normalizing size activities adapts datasets', 'bounded degree brandt significant frugal recent defective arxiv local solved', 'probability memory traveling strategy maximize locations computational path takes accumulated', 'best bound revelation improvement chang providing essentially rounds include showed', 'maximization greedy modularity popular insight algorithmic understood achieved quantitative mechanism', 'models layer proposed normalization adaptive introduce approach results dynamically environments', 'applications author suggested presentation cft yangian analog suggestion quantized result', 'cases linear network response palmer mean anderson belief ordinary ising', 'fixed extends phases maximal continuous let multidimensional modulating operator define', 'epsilon finite goal provide strategies maximizes locations distance according formalizing', 'results non propagation code numerical models time model nonlinear pulsedyn', 'lstm stability vectors variability accuracy adapting benchmark bidirectional introduced networks', 'box parameter free dynamical dimension allows achieve solve broadly potentials', 'dynamically technique parameters deep normalization require generating environments speakers adaptation', 'log algorithm graphs problems number complexity local omega graph node', 'rewards time problems reward optimal model study dynamically question processes', 'greedy maximization modularity insight popular algorithmic level rapid ease fails', 'method susceptibility based new improved random structures approaches combining linear', 'supergravity shown supersymmetric limit orders dual presented background duality explicitly', 'stochastic nodes epsilon consider robot expected finite optimal generated paths', 'parameter recurrence dynamical accurate transparency box free source simulations easy', 'approximate network constructed mean ordinary anderson diagonal equation markov concept', 'currently list mathsf ideas solved vertex conjectured labeling upper locally', 'computational average visiting accumulated probability establish general potential collection appear']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 3332.78it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 4997.38it/s]
Training FASTopic: 100%|██████████| 101/101 [00:03<00:00, 31.40it/s]
[I 2025-12-05 19:09:13,126] Trial 12 finished with value: -1000000.0 and parameters: {'num_topics': 22, 'DT_alpha': 1.0, 'normalize_embeddings': True, 'learning_rate': 0.011782800596762824, 'epochs': 101}. Best is trial 0 with value: -1000000.0.

Top words found: ['ads calabi unique conjectural holds suggestion yau identification classical enumerative', 'sphere author applications guella cross covariances earth goes raised multiple', 'acoustic models layer normalization neural dln dynamically adaptation parameters speakers', 'sphere modelling question schoenberg obstacle functions case similarly follows related', 'propagation numerical field study computing processes open particle program iii', 'susceptibility method new based mean fields concept inverse robust anderson', 'degree bounded problems complexity node frugal showed labeling recent automatically', 'mathbb theorem carleson polynomial mathbf infty define lies kernel maximal', 'rule issue rapid communication community fails counting level achieved estimating', 'model data classification clustering outliers bayesian missing mixture modelling normal', 'having scale inference gives treatment latent developed restrictive possibility distributions', 'adaptive proposed wsj vectors apply lstm noises recognition dynamic improves', 'results non pulsedyn nonlinear code integrable pasta lennard fermi toda', 'problems consider expected paths nodes node based graph problem step', 'algebra theory omega koszul operators background shown presented supergravity branes', 'accurate dynamical ensure excitation potentials phenomenon solve source broadly black', 'graphs algorithm approach algorithms local number prove making results solved', 'log pettie lll coloring round known chung randomized sqrt lcl', 'paper large terms scaling training evaluate introduced recently asr bidirectional', 'time rewards reward optimal epsilon robot horizon infinite stochastic finite', 'provides popular greedy maximization algorithmic modularity insight risk presumably detection', 'asks traveling according edges collects total unit distance path potential']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 3166.95it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 5000.96it/s]
Training FASTopic: 100%|██████████| 136/136 [00:03<00:00, 36.58it/s]
[I 2025-12-05 19:09:18,600] Trial 13 finished with value: -1000000.0 and parameters: {'num_topics': 65, 'DT_alpha': 5.0, 'normalize_embeddings': False, 'learning_rate': 0.004100966689715586, 'epochs': 136}. Best is trial 0 with value: -1000000.0.

Top words found: ['presented branes background shown supergravity dual gravitational explicitly perturbation orders', 'combining constructed inverse improved fields response matching formulate reduced approaches', 'let truncations define phases zygmund multidimensional operator continuous standard lies', 'paths edges accumulated provide unit potential according disappear path objectives', 'rewards optimal time nodes epsilon stochastic finite study horizon computing', 'non nonlinear code pasta pulsedyn specialists accessible dynamics toda body', 'sphere characterisation definite survey multiple products schoenberg earth lines related', 'modelling sphere guella goes weather cross position related author peron', 'allow distributions focuses developed processed latent normal treatment variables scale', 'distributed brandt lcl automatically enlightening recent frugal include labeling conjecture', 'recently lium introduced channel asr vocabulary training neurons lstm networks', 'lemma relaxed progress conjectured solved showed upper locally sped classic', 'supergravity shown supersymmetric duality branes presented terms large paper orders', 'acoustic dynamically neural normalization dln proposed layer new require adaptive', 'models layer dln normalization neural adaptive parameters technique deep environments', 'sphere spheres follows prediction long menegatto motivation case berg extending', 'robust belief markov structures approximate concept mean response thouless special', 'classification data model clustering paper bayesian mixture based outliers missing', 'benchmark speaker speed recognition scaling channel bidirectional unlike variability activities', 'quantized dimensional unable holds result unique suggested operation suggestion classical', 'general maximize memory asks compute computational probability disappear total collection', 'limit popular local graphs algorithms algorithm number communication insight typically', 'optimal horizon problems stochastic rewards epsilon consider graph paths graphs', 'complexity node graph problem lower step arbitrary algorithm graphs problems', 'continues issue forming rule implementation level sparsity performance mechanism quantitative', 'bounded theorem degree kernel extends lies maximal define modulating truncations', 'mathbb polynomial carleson mathbf fixed theorem obtained standard modulating multidimensional', 'algorithmic modularity greedy presumably popular insight maximization approach estimating apart', 'sphere obstacle geotemporal position raised extensions lines answered long definite', 'defective significant vertex mathsf solving labeling list currently variant revelation', 'integrable morse fermi code body soliton obtained dynamics lennard tsingou', 'reduced matching response inverse approaches diagonal fields thouless improved structures', 'time study numerical sphere question applications geostatistical functions porcu positive', 'algebraic checked analog identification formulation result quantization presentation calabi constants', 'states ease offer understood rapid detection persistently rule implementation sparsity', 'phenomenon solve single recurrence excitation source particle iii ensure free', 'establish takes accumulated disappears probability compute edges according locations given', 'reward robot infinite generated epsilon rewards optimal model based time', 'randomized best improvement chang lcl sqrt chung rounds bound include', 'perturbation arxiv explicitly orders duality gravitational dual supersymmetric double variable', 'outliers bayesian missing mixture clustering having handle scale restrictive sensitivity', 'method susceptibility cases based linear field random new ordinary equation', 'approach algorithms insight maximization greedy popular number proposed modularity local', 'normalizing datasets apply stability generates evaluate speech adapting neurons shifting', 'greedy maximization modularity insight failure popular algorithmic achieved detection estimating', 'missing mixture outliers bayesian clustering modelling supervised method introduction handle', 'problems palmer network random computation equation constructed diagonal improved approximate', 'collision examine students equilibrium particle recurrence dynamical file state parameter', 'jones systems soliton ulam lennard code dynamics tsingou body morse', 'degree round coloring lll bounded chung sqrt randomized lcl pettie', 'broadly dynamical interface ensure designed distribute iii collision useful achieve', 'adaptation deep speakers environments technique parameters improve introduce layer terms', 'ted vectors transcription size wsj accuracy generates adapts scaling modeling', 'log graphs algorithm problems pettie local number lcl algorithms known', 'discrete process encode visiting propose collected goal collects average strategy', 'adopted values learning gives inference sensitivity possibility missing latent processed', 'parameter program decay dimension rich quasi achieve simulations file easy', 'algebra theory koszul operators omega background non branes presented shown', 'question sphere study numerical raised time type peron author line', 'infty operators double variable coupling form twisted yau ads threefolds', 'propagation susceptibility adaptive field proposed linear new method cases based', 'theorem continuous multidimensional phases operator let zygmund standard obtained modulating', 'results numerical pulsedyn non nonlinear propagation code study models introduce', 'factors speaker shifting unlike recognition modeling experiments improves bidirectional release', 'cft constants certain yangian explicit classical geometry loop dimensional analog']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 3334.37it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 10022.23it/s]
Training FASTopic: 100%|██████████| 82/82 [00:01<00:00, 59.00it/s]
[I 2025-12-05 19:09:21,725] Trial 14 finished with value: -1000000.0 and parameters: {'num_topics': 26, 'DT_alpha': 1.0, 'normalize_embeddings': False, 'learning_rate': 0.0014884623150573028, 'epochs': 82}. Best is trial 0 with value: -1000000.0.

Top words found: ['method based formulate diagonal reduced inverse markov ising constructed palmer', 'carleson polynomial mathbb mathbf standard operator modulating extends define zygmund', 'algebra theory omega operators supergravity koszul supersymmetric background branes shown', 'long related covariances extending schoenberg guella menegatto peron goes raised', 'states communication better fails risk forming clear update ease level', 'generated expected finite existing traveling modeled edges strategy establish computational', 'body ulam soliton toda lennard specialists non systems dynamics code', 'question modelling inference handle approximation values focuses variables allow latent', 'infty double formulated twisted ads calabi conjectural checked operation threefolds', 'algorithmic greedy modularity maximization insight popular algorithms detection typically continues', 'degree round rounds lcl distributed lll include chang progress pettie', 'log coloring complexity algorithm sqrt graphs lower step problems problem', 'collision phenomenon rich black equipartitioned iii setting examine achieve state', 'morse results pulsedyn computing tsingou processes pasta nonlinear accessible jones', 'chung defective lemma showed enlightening brandt currently providing revelation local', 'optimal reward rewards horizon infinite stochastic robot epsilon nodes consider', 'approach arising proposed stability accuracy training additional activities transcription apply', 'classification missing outliers clustering mixture bayesian data processed developed having', 'numerical study literature recurrence anticipate easy quasi chain benchmarking parameter', 'phases obtained continuous multidimensional maximal theorem kernel lies bounded truncations', 'dynamically acoustic layer neural normalization models dln parameters deep adaptation', 'susceptibility fields network computation improved propagation concept ordinary special random', 'fixed generating require release noises vocabulary recognition experimental experiments factors', 'gravitational dual duality presented correspondence unable constants perturbation classical unique', 'terms large paper lium generates datasets called ted networks unlike', 'sphere cross case multiple obstacle follows definite products earth answered']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 3332.78it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 5000.96it/s]
Training FASTopic: 100%|██████████| 27/27 [00:01<00:00, 20.26it/s]
[I 2025-12-05 19:09:24,809] Trial 15 finished with value: -1000000.0 and parameters: {'num_topics': 63, 'DT_alpha': 5.0, 'normalize_embeddings': True, 'learning_rate': 0.02192703868720986, 'epochs': 27}. Best is trial 0 with value: -1000000.0.

Top words found: ['models introduce lium additional factors model neurons asr experimental shifting', 'problems formalizing objectives modeled traveling appear probability collects memory general', 'transparency scientifically equipartitioned rich chains source easy excitation simulations broadly', 'palmer constructed inverse formulate approximate equation ordinary random concept matching', 'linear computation cases reduced ising structures combining belief random improved', 'greedy popular maximization modularity approach issue insight offer algorithmic detection', 'sphere bochner peron extensions prediction geotemporal guella lines case functions', 'variability unlike stability training benchmark evaluate wsj noises introduced channel', 'optimal time epsilon robot nodes stochastic question expected generated routing', 'non pulsedyn known processes computing tsingou soliton making study code', 'communication rapid mechanism implementation persistently typically continues sparsity level risk', 'propagation field method based adaptive proposed cases new linear robust', 'rewards reward horizon infinite stochastic node epsilon graph finite paths', 'nonlinear lennard integrable systems jones code pasta fermi body ulam', 'theory explicitly supersymmetric duality non arxiv terms large orders perturbation', 'dynamically environments speakers adaptation parameters normalization deep technique dln generating', 'insight algorithmic counting community clear apart ease forming states fails', 'maximizes visiting asks edges provide computational locations disappear distance path', 'lcl round coloring randomized rounds sqrt bound chung improvement lll', 'acoustic neural layer dln normalization technique speakers adaptation deep parameters', 'data paper ted accuracy speaker release generates information adapts channel', 'propagation field dynamics specialists ulam equilibrium state recover body code', 'checked ads linear unique formulated cft certain dimensional result double', 'recognition adapting improves dynamic speed size experiments bidirectional transcription apply', 'log pettie lll coloring round randomized local chung sqrt omega', 'numerical results setting dynamical dimension particle solve allows iii program', 'truncations define fixed maximal phases modulating let extends kernel standard', 'lies standard mathbf zygmund modulating extends phases multidimensional continuous fixed', 'study dynamically new computing require based processes generating model existing', 'graphs algorithm problems complexity node step arbitrary problem graph lower', 'conjectured providing variant brandt upper showed ideas classic defective sped', 'equipartitioned transparency scientifically rich chains easy students source simulations distribute', 'paths generated routing consider robot finite expected stochastic graph epsilon', 'branes supergravity background shown dual gravitational duality koszul perturbation paper', 'carleson theorem mathbb mathbf multidimensional modulating kernel extends phases maximal', 'limit lower problem arbitrary graph unit complexity step average node', 'algebra koszul operators presented omega shown background limit supergravity arxiv', 'susceptibility markov diagonal fields network special approaches structures computation reduced', 'adopted variables processed normal having bayesian possibility values approximation gives', 'learning bayesian treatment variational values gives normal possibility focuses processed', 'classification mixture clustering outliers missing model based bayesian values method', 'code toda morse accessible specialists fermi pasta jones body ulam', 'author applications question time study numerical raised motivation products follows', 'bayesian method distributions values approximation based focuses treatment gives adopted', 'orders perturbation identification suggestion yangian constants certain yau formulated double', 'infty operator operators continuous let zygmund extends maximal fixed calabi', 'proposed adaptive approach improve fixed deep new large results generating', 'concept thouless approximate matching improved robust response anderson mean belief', 'earth follows similarly products answered porcu sphere type geostatistical characterisation', 'applications author quantized threefolds conjectural holds presentation coupling enumerative quantum', 'noises normalizing called modeling size apply introduced scaling channel recently', 'guella goes functions covariances extensions weather sphere schoenberg cross case', 'better failure understood risk mechanism rule update detection implementation metastable', 'degree bounded distributed include best known chang prove making bound', 'recent lemma solved sped progress mathsf relaxed conjecture enlightening run', 'modelling scale inference latent developed allow restrictive supervised variational introduction', 'useful literature localized anticipate box students designed equilibrium chain quasi', 'spheres definite positive multiple long type porcu menegatto related line', 'suggested cft twisted determine geometry formulation form correspondence stack operation', 'labeling vertex revelation checkable frugal locally automatically currently significant essentially', 'polynomial obtained bounded degree kernel multidimensional extends modulating standard mathbf', 'strategies collection strategy disappear collected establish given distance disappears goal', 'algorithms number local limit provides proposed approach presumably results performance']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 3008.83it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 10015.05it/s]
Training FASTopic: 100%|██████████| 144/144 [00:09<00:00, 14.64it/s]
[I 2025-12-05 19:09:36,441] Trial 16 finished with value: -1000000.0 and parameters: {'num_topics': 80, 'DT_alpha': 15.0, 'normalize_embeddings': True, 'learning_rate': 0.0050854695413663316, 'epochs': 144}. Best is trial 0 with value: -1000000.0.

Top words found: ['multidimensional kernel zygmund lies operator continuous extends phases let define', 'fails states mechanism persistently quantitative risk offer presumably community level', 'rewards time reward optimal model stochastic study epsilon infinite horizon', 'frugal currently providing vertex relaxed lemma revelation automatically ideas essentially', 'special random network markov robust concept ising structures approximate equation', 'nonlinear code pulsedyn dynamics pasta toda soliton tsingou morse integrable', 'conjectural classical suggested cft formulated explicit identification stack dimensional determine', 'acoustic models layer normalization neural dln dynamically adaptive technique introduce', 'generated routing paths nodes infinite finite expected consider optimal stochastic', 'correspondence checked formulation quantization double enumerative explicit conjectural holds unable', 'lll pettie coloring round known chung omega randomized lcl sqrt', 'truncations maximal fixed define lies modulating standard operator extends zygmund', 'gravitational shown supersymmetric background duality explicitly dual orders perturbation supergravity', 'parameters speakers environments deep activities adaptation transcription channel asr datasets', 'missing outliers clustering mixture bayesian classification method modelling based data', 'let standard define phases multidimensional fixed modulating lies extends maximal', 'algorithms graphs algorithm number local approach proposed limit results maximization', 'chain interface equilibrium benchmarking setting transparency dimension recover box black', 'method based susceptibility linear mean ising response belief palmer anderson', 'unique threefolds presentation determine operation coupling constants algebraic quantized variable', 'network robust computation constructed inverse improved equation structures approximate ordinary', 'approximate network inverse improved constructed ordinary robust diagonal structures computation', 'sphere long motivation similarly case guella definite lines line raised', 'omega koszul branes presented shown background supergravity perturbation dual gravitational', 'dln dynamically proposed neural normalization approach adaptive models layer results', 'environments parameters deep speakers adaptation technique training wsj variability additional', 'improvement bound chang distributed rounds include best randomized chung sqrt', 'approach popular insight maximization modularity algorithmic greedy algorithms update provides', 'possibility having sensitivity focuses values processed approximation allow variational treatment', 'time study numerical question results sphere applications author line earth', 'mathbf polynomial mathbb carleson theorem fixed continuous bounded modulating operator', 'bayesian outliers mixture clustering missing introduction supervised processed restrictive scale', 'ordinary network diagonal equation approaches formulate computation inverse improved robust', 'visiting appear existing strategies collects propose given provide collected disappears', 'sphere modelling berg porcu extending geostatistical obstacle case definite line', 'log degree algorithm graphs problems bounded results algorithms number local', 'classification model data paper based method missing mixture clustering outliers', 'sqrt lcl randomized chung local number round pettie coloring rounds', 'robot infinite optimal reward epsilon stochastic horizon consider rewards finite', 'sphere position goes multiple covariances schoenberg weather answered cross bochner', 'sphere survey geostatistical prediction covariances case raised goes functions porcu', 'designed allows solve anticipate ensure equilibrium collision transparency free simulations', 'sphere survey geostatistical motivation similarly lines geotemporal raised covariances functions', 'examine potentials scientifically distribute iii chains allows file decay particle', 'bounded theorem mathbb carleson degree polynomial mathbf fixed continuous obtained', 'speech release arising vectors unlike shifting benchmark information called apply', 'results non propagation numerical pulsedyn code models nonlinear time study', 'pulsedyn nonlinear code accessible body ulam non morse jones dynamics', 'bounds takes goal collection compute distance provide modeled establish encode', 'insight modularity algorithmic greedy popular maximization approach provides sparsity rule', 'result formulated constants twisted classical unique certain suggestion threefolds geometry', 'computing processes parameter recurrence distribute program model broadly dimension achieve', 'obtained truncations maximal kernel define standard extends phases lies multidimensional', 'nonlinear non code pulsedyn systems integrable pasta soliton tsingou ulam', 'cases linear mean markov constructed inverse matching approximate computation belief', 'greedy algorithmic maximization popular modularity insight approach apart rule estimating', 'adaptive adaptation technique speakers deep environments parameters dln large terms', 'network improved diagonal approximate inverse structures robust equation approaches random', 'duality shown explicitly orders perturbation supersymmetric background supergravity presented gravitational', 'vocabulary apply benchmark factors dynamic bidirectional information lstm recently adapts', 'susceptibility propagation new adaptive proposed problems field method based cases', 'infty operators modulating truncations standard define operator extends maximal let', 'sensitivity values focuses treatment approximation allow adopted variational scale having', 'bayesian outliers clustering treatment having values variational allow distributions approximation', 'datasets recognition dynamic lium speaker stability generates vectors neurons information', 'complexity problem step lower arbitrary node graph best chung randomized', 'problems node graph rewards optimal horizon epsilon robot reward stochastic', 'mechanism counting level achieved typically community performance risk offer detection', 'implementation fails persistently presumably level offer failure quantitative states issue', 'bayesian outliers clustering mixture missing adopted introduction gives normal learning', 'obtained setting solve free achieve localized state iii equilibrium single', 'algebra theory operators koszul supergravity non presented background omega branes', 'accumulated asks maximizes probability appear edges optimization disappear average path', 'general maximize formalizing disappears establish strategies computational compute potential discrete', 'list defective classic lemma locally ideas essentially providing upper enlightening', 'modularity insight greedy algorithmic maximization popular understood level failure better', 'sphere motivation follows extensions authors positive cross answered related bochner', 'noises modeling parameters experiments networks normalizing neurons recently ted scaling', 'variant conjecture automatically mathsf progress recent enlightening run conjectured labeling', 'bayesian outliers clustering mixture normal gives distributions possibility missing restrictive']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 3329.61it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 6656.57it/s]
Training FASTopic: 100%|██████████| 200/200 [00:06<00:00, 30.27it/s]
[I 2025-12-05 19:09:44,998] Trial 17 finished with value: -1000000.0 and parameters: {'num_topics': 46, 'DT_alpha': 10.0, 'normalize_embeddings': False, 'learning_rate': 0.0024867951589597247, 'epochs': 200}. Best is trial 0 with value: -1000000.0.

Top words found: ['acoustic models dln layer neural normalization dynamically adaptive proposed new', 'missing clustering mixture outliers processed distributions allow learning variables treatment', 'coloring lcl sqrt chung lll complexity pettie randomized round known', 'carleson bounded degree obtained infty mathbf mathbb operators fixed operator', 'values gives treatment handle approximation latent having scale developed normal', 'kernel continuous define lies multidimensional zygmund let truncations extends operator', 'conjectural holds presentation explicit quantum formulation enumerative identification formulated quantized', 'code nonlinear systems accessible body pasta tsingou dynamics integrable lennard', 'diagonal markov random ising approaches response formulate constructed matching computation', 'popular modularity insight greedy algorithmic maximization approach presumably risk provides', 'explicitly duality presented supersymmetric dual suggestion perturbation background ads branes', 'restrictive possibility latent variational developed sensitivity introduction gives adopted inference', 'adapts accuracy modeling introduced recently vocabulary factors apply dynamic networks', 'coupling determine result unique dimensional loop calabi certain stack operation', 'modularity algorithmic maximization insight popular greedy implementation community clear mechanism', 'conjecture progress lemma recent ideas run vertex defective brandt mathsf', 'unlike improves normalizing datasets training wsj called evaluate shifting variability', 'algebra theory koszul operators omega shown branes background presented non', 'algorithms approach local greedy insight algorithmic popular number modularity maximization', 'chains free file useful potentials equilibrium localized scientifically phenomenon open', 'issue offer continues states maximization update failure detection quantitative mechanism', 'nodes consider node paths expected routing generated lower optimal stochastic', 'log degree graphs algorithm problems round bounded pettie lll local', 'decay dynamical transparency source allows recover quasi simulations broadly phenomenon', 'sphere similarly authors lines weather bochner raised answered peron multiple', 'distributed best include chung rounds improvement bound randomized chang conjectured', 'easy chain ensure broadly program benchmarking parameter recurrence collision source', 'theorem polynomial mathbb mathbf carleson phases modulating standard let infty', 'sped revelation relaxed showed locally enlightening essentially frugal upper labeling', 'classification bayesian data model outliers mixture clustering missing paper based', 'strategy appear takes average formalizing goal compute unit bounds distance', 'examine setting file equilibrium students quasi interface anticipate scientifically state', 'modelling sphere case guella cross long covariances motivation position porcu', 'maximize zygmund define asks maximizes optimization continuous kernel disappear maximal', 'adaptive new cases ordinary proposed anderson computation matching constructed approaches', 'adaptation environments deep technique speakers parameters large terms require fixed', 'traveling edges strategies existing visiting collection establish probability process encode', 'rewards reward horizon optimal problems infinite robot graph time model', 'stochastic epsilon optimal finite reward generated robot routing infinite paths', 'belief network fields structures concept ising reduced formulate combining approximate', 'non results pulsedyn numerical nonlinear code propagation study models specialists', 'supergravity orders supersymmetric dual duality presented gravitational perturbation background branes', 'environments speakers technique parameters deep adaptation channel factors asr recognition', 'time study numerical sphere question definite obstacle prediction results geostatistical', 'functions sphere goes answered menegatto type geotemporal schoenberg earth raised', 'susceptibility propagation method inverse based mean field improved robust problems']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 3990.39it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 5000.96it/s]
Training FASTopic: 100%|██████████| 148/148 [00:04<00:00, 30.58it/s]
[I 2025-12-05 19:09:51,570] Trial 18 finished with value: -1000000.0 and parameters: {'num_topics': 20, 'DT_alpha': 5.0, 'normalize_embeddings': False, 'learning_rate': 0.018158532922746568, 'epochs': 148}. Best is trial 0 with value: -1000000.0.

Top words found: ['modelling developed introduction processed variational latent sensitivity scale restrictive adopted', 'algorithms approach popular insight greedy algorithmic maximization modularity results local', 'model classification data mixture missing outliers bayesian clustering method based', 'operators orders correspondence stack analog certain geometry unique calabi conjectural', 'log problems algorithm coloring lll pettie graphs round degree chung', 'rounds distributed best include solved currently revelation recent frugal conjecture', 'acoustic models layer normalization neural dln dynamically speakers technique deep', 'sphere time modelling line obstacle weather peron characterisation raised long', 'time model study question processes computing locations strategy asks bounds', 'modularity maximization algorithmic greedy insight popular community sparsity detection update', 'propagation susceptibility method based proposed belief combining palmer inverse concept', 'infty operators obtained theorem mathbb polynomial carleson mathbf degree bounded', 'algebra theory koszul omega shown presented branes background supergravity explicitly', 'time sphere study numerical results question applications author survey authors', 'results nonlinear code pulsedyn non tsingou toda jones systems accessible', 'localized phenomenon dynamical allows obtained equilibrium transparency free equipartitioned chains', 'rewards reward optimal stochastic infinite robot epsilon horizon expected generated', 'bounded mathbf carleson polynomial mathbb theorem fixed lies zygmund truncations', 'problems node graph complexity step arbitrary problem lower graphs algorithm', 'vectors transcription datasets scaling additional adapting activities training experimental shifting']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 3329.34it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 10010.27it/s]
Training FASTopic: 100%|██████████| 92/92 [00:01<00:00, 51.63it/s]
[I 2025-12-05 19:09:55,136] Trial 19 finished with value: -1000000.0 and parameters: {'num_topics': 39, 'DT_alpha': 1.0, 'normalize_embeddings': True, 'learning_rate': 0.0010519095028133836, 'epochs': 92}. Best is trial 0 with value: -1000000.0.

Top words found: ['linear cases identification double operation twisted threefolds ads form geometry', 'brandt recent showed mathsf solving defective lemma frugal revelation essentially', 'classification missing mixture outliers sensitivity clustering bayesian gives adopted values', 'memory traveling probability appear general path collects formalizing objectives graph', 'allow focuses approximation data latent learning possibility developed variational introduction', 'labeling solved providing automatically significant known conjectured classic checkable conjecture', 'understood performance metastable algorithms mechanism rule fails typically counting maximization', 'collected discrete potential goal encode strategies average maximizes accumulated existing', 'polynomial zygmund maximal lies truncations continuous define multidimensional operator obtained', 'sphere covariances weather type positive motivation extending obstacle extensions menegatto', 'degree coloring round pettie chung lll bound randomized best bounded', 'related question follows position schoenberg porcu geostatistical case geotemporal long', 'shown duality gravitational orders perturbation terms algebra explicitly correspondence supersymmetric', 'integrable tsingou introduce morse jones specialists lennard toda systems ulam', 'presumably apart greedy level ease better estimating algorithmic achieved persistently', 'results pulsedyn code dynamics soliton body pasta fermi nonlinear accessible', 'chain localized iii examine useful parameter source single benchmarking excitation', 'carleson mathbb theorem mathbf modulating standard fixed let phases extends', 'computing processes phenomenon setting simulations scientifically allows equilibrium systems collision', 'reward rewards robot horizon stochastic infinite epsilon routing time generated', 'number lcl include chang lll list distributed local upper rounds', 'method formulate approaches combining special random ising inverse fields propagation', 'susceptibility response palmer matching improved constructed robust belief ordinary network', 'dln neural technique layer speakers environments adaptation models parameters normalization', 'products cross raised authors berg answered similarly characterisation obstacle spheres', 'analog quantization enumerative dimensional unique coupling constants yau algebraic formulated', 'presented supergravity koszul branes theory algebra operators background dual perturbation', 'dynamically speakers recently deep adaptation environments experimental speed activities benchmark', 'proposed adaptive mean equation approximate network reduced thouless fields markov', 'provides ulam making systems prove nonlinear dimension chains decay soliton', 'algorithm sqrt log local graphs improvement randomized improve best distributed', 'handle processed modelling data restrictive paper introduction inference having values', 'node optimal graph problem step lower problems arbitrary complexity expected', 'release recognition evaluate bidirectional stability noises apply unlike modeling transcription', 'numerical particle solve field students state black potentials broadly study', 'popular approach modularity insight algorithmic sparsity failure provides maximization update', 'propose disappear given disappears computational bounds strategy visiting expected locations', 'omega certain arxiv loop result unable holds formulation quantum explicitly', 'acoustic normalization layer deep parameters adaptation dynamically neural models speakers']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids
Mejor coherencia: -1000000.0
Mejores hiperparámetros: {'num_topics': 36, 'DT_alpha': 1.0, 'normalize_embeddings': True, 'learning_rate': 0.05399484409787434, 'epochs': 128}

In [16]:

# ========== Reentrenar el mejor modelo con los mejores hiperparámetros ==========
best = study.best_params
print("Reentrenando FASTopic con:", best)

# Intentar crear modelo con esos parámetros

best_model = FASTopic(num_topics=best["num_topics"],
                      normalize_embeddings=best.get("normalize_embeddings", True),
                      DT_alpha=best.get("DT_alpha", 5.0),
                      low_memory=best.get("low_memory", False),
                      device=best.get("device", "cpu"),
                      verbose=True)


# Fit final (intentar con lr/epochs)

best_top_words, best_doc_topic_dist = best_model.fit_transform(clean_text, learning_rate=best.get("learning_rate", 0.01), epochs=best.get("epochs", 100))

2025-12-05 19:11:03,093 - FASTopic - use device: cpu
2025-12-05 19:11:03,094 - FASTopic - First fit the model.

Reentrenando FASTopic con: {'num_topics': 36, 'DT_alpha': 1.0, 'normalize_embeddings': True, 'learning_rate': 0.05399484409787434, 'epochs': 128}

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 5000.36it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 3988.50it/s]
C:\Users\zeldan\anaconda3\envs\tfg-topics2\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning:

The parameter 'token_pattern' will not be used since 'tokenizer' is not None'

2025-12-05 19:11:04,636 - TopMost - Real vocab size: 498
2025-12-05 19:11:04,636 - TopMost - Real training size: 10 	 avg length: 79.300

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Training FASTopic:   4%|▍         | 5/128 [00:00<00:02, 47.33it/s]2025-12-05 19:11:05,240 - FASTopic - Epoch: 010 loss: 365.517
Training FASTopic:  15%|█▍        | 19/128 [00:02<00:17,  6.07it/s]2025-12-05 19:11:07,159 - FASTopic - Epoch: 020 loss: 351.348
Training FASTopic:  23%|██▎       | 29/128 [00:04<00:23,  4.30it/s]2025-12-05 19:11:09,534 - FASTopic - Epoch: 030 loss: 342.352
Training FASTopic:  30%|███       | 39/128 [00:06<00:10,  8.39it/s]2025-12-05 19:11:10,995 - FASTopic - Epoch: 040 loss: 336.837
Training FASTopic:  38%|███▊      | 48/128 [00:07<00:09,  8.55it/s]2025-12-05 19:11:12,047 - FASTopic - Epoch: 050 loss: 334.799
Training FASTopic:  45%|████▌     | 58/128 [00:07<00:06, 11.27it/s]2025-12-05 19:11:12,873 - FASTopic - Epoch: 060 loss: 333.661
Training FASTopic:  53%|█████▎    | 68/128 [00:08<00:04, 13.75it/s]2025-12-05 19:11:13,556 - FASTopic - Epoch: 070 loss: 332.801
Training FASTopic:  62%|██████▏   | 79/128 [00:09<00:02, 16.50it/s]2025-12-05 19:11:14,136 - FASTopic - Epoch: 080 loss: 332.252
Training FASTopic:  70%|██████▉   | 89/128 [00:09<00:02, 19.33it/s]2025-12-05 19:11:14,630 - FASTopic - Epoch: 090 loss: 331.870
Training FASTopic:  77%|███████▋  | 99/128 [00:10<00:02, 14.20it/s]2025-12-05 19:11:15,349 - FASTopic - Epoch: 100 loss: 331.542
Training FASTopic:  85%|████████▌ | 109/128 [00:11<00:01, 13.43it/s]2025-12-05 19:11:16,106 - FASTopic - Epoch: 110 loss: 331.236
Training FASTopic:  93%|█████████▎| 119/128 [00:11<00:00, 12.89it/s]2025-12-05 19:11:16,836 - FASTopic - Epoch: 120 loss: 331.196
Training FASTopic: 100%|██████████| 128/128 [00:12<00:00, 10.07it/s]

Topic 0: code pulsedyn nonlinear ulam tsingou toda soliton systems body lennard dynamics specialists pasta integrable accessible
Topic 1: theorem mathbf mathbb polynomial carleson bounded kernel zygmund phases continuous maximal standard operator modulating lies
Topic 2: algebra theory omega koszul shown presented supergravity background branes explicitly orders supersymmetric dual duality gravitational
Topic 3: non numerical obtained fermi decay morse accessible black examine equilibrium recurrence source dynamical distribute quasi
Topic 4: log coloring round pettie number known randomized chung lcl making prove algorithm results recent defective
Topic 5: optimization formalizing modeled bounds average maximizes establish collected total goal given asks takes appear according
Topic 6: question sphere type extensions products extending schoenberg porcu prediction cross survey position similarly goes berg
Topic 7: modelling covariances obstacle geostatistical peron authors menegatto long functions earth guella lines follows berg motivation
Topic 8: carleson mathbb polynomial theorem mathbf bounded truncations extends let operator zygmund modulating lies continuous define
Topic 9: results provides students single introduce simulations particle making benchmarking collision broadly algorithms distribute quasi limit
Topic 10: method ising combining special network concept fields approximate formulate thouless inverse computation approaches structures robust
Topic 11: additional datasets release information activities adapting apply experiments experimental factors channel generates deep speakers adaptation
Topic 12: sqrt chang essentially brandt classic locally defective conjectured ideas upper lemma enlightening frugal vertex relaxed
Topic 13: algorithm graphs local problem lower run providing variant showed checkable labeling solved algorithms making log
Topic 14: perturbation dual supersymmetric duality yau formulated checked calabi determine holds yangian formulation algebraic coupling geometry
Topic 15: degree lll bounded bound best rounds improvement distributed include conjecture list sqrt revelation automatically mathsf
Topic 16: perturbation dual supersymmetric applications result operation unique constants conjectural twisted double stack quantization suggested variable
Topic 17: rewards optimal reward horizon stochastic robot infinite epsilon consider expected nodes finite routing paths generated
Topic 18: paper data fixed large terms arxiv improve infty bounded cases explicitly model orders gravitational operators
Topic 19: models acoustic dynamically dln normalization layer neural generating require introduce limit technique environments parameters adaptation
Topic 20: limit rewards maximizes modeled formalizing bounds optimization average establish collected goal according takes appear given
Topic 21: model classification mixture bayesian missing clustering outliers distributions normal variables gives adopted learning treatment inference
Topic 22: modelling developed handle supervised possibility variational having approximation values allow processed scale restrictive focuses introduction
Topic 23: problems graph complexity node step arbitrary graphs algorithm local run providing variant showed labeling checkable
Topic 24: environments parameters technique adaptation speakers deep acoustic neural layer normalization modeling recognition stability wsj called
Topic 25: author applications answered definite multiple line related geotemporal case modelling positive bochner spheres similarly position
Topic 26: algorithms states offer typically presumably update performance failure metastable issue continues risk communication level persistently
Topic 27: time model based study processes computing memory discrete require modelling limit sphere prediction porcu type
Topic 28: propagation susceptibility field equation constructed response mean matching anderson markov diagonal reduced belief ordinary random
Topic 29: new linear cases palmer improved limit adaptive proposed additional structures random robust ordinary method propagation
Topic 30: algorithms ease mechanism forming rapid better fails sparsity issue rule level communication understood continues failure
Topic 31: similarly follows survey raised berg goes characterisation position spheres motivation bochner positive functions obstacle guella
Topic 32: approach popular greedy algorithmic maximization insight modularity limit achieved detection algorithms ease rapid clear quantitative
Topic 33: proposed adaptive additional release information activities limit adapting experimental apply datasets experiments factors improved new
Topic 34: students introduce single particle collision broadly benchmarking simulations jones distribute quasi allows chain open accurate
Topic 35: operators gravitational infty duality explicitly orders supersymmetric dual perturbation applications checked result holds twisted unique

In [17]:
best_model.get_top_words()

Topic 0: code pulsedyn nonlinear ulam tsingou toda soliton systems body lennard dynamics specialists pasta integrable accessible
Topic 1: theorem mathbf mathbb polynomial carleson bounded kernel zygmund phases continuous maximal standard operator modulating lies
Topic 2: algebra theory omega koszul shown presented supergravity background branes explicitly orders supersymmetric dual duality gravitational
Topic 3: non numerical obtained fermi decay morse accessible black examine equilibrium recurrence source dynamical distribute quasi
Topic 4: log coloring round pettie number known randomized chung lcl making prove algorithm results recent defective
Topic 5: optimization formalizing modeled bounds average maximizes establish collected total goal given asks takes appear according
Topic 6: question sphere type extensions products extending schoenberg porcu prediction cross survey position similarly goes berg
Topic 7: modelling covariances obstacle geostatistical peron authors menegatto long functions earth guella lines follows berg motivation
Topic 8: carleson mathbb polynomial theorem mathbf bounded truncations extends let operator zygmund modulating lies continuous define
Topic 9: results provides students single introduce simulations particle making benchmarking collision broadly algorithms distribute quasi limit
Topic 10: method ising combining special network concept fields approximate formulate thouless inverse computation approaches structures robust
Topic 11: additional datasets release information activities adapting apply experiments experimental factors channel generates deep speakers adaptation
Topic 12: sqrt chang essentially brandt classic locally defective conjectured ideas upper lemma enlightening frugal vertex relaxed
Topic 13: algorithm graphs local problem lower run providing variant showed checkable labeling solved algorithms making log
Topic 14: perturbation dual supersymmetric duality yau formulated checked calabi determine holds yangian formulation algebraic coupling geometry
Topic 15: degree lll bounded bound best rounds improvement distributed include conjecture list sqrt revelation automatically mathsf
Topic 16: perturbation dual supersymmetric applications result operation unique constants conjectural twisted double stack quantization suggested variable
Topic 17: rewards optimal reward horizon stochastic robot infinite epsilon consider expected nodes finite routing paths generated
Topic 18: paper data fixed large terms arxiv improve infty bounded cases explicitly model orders gravitational operators
Topic 19: models acoustic dynamically dln normalization layer neural generating require introduce limit technique environments parameters adaptation
Topic 20: limit rewards maximizes modeled formalizing bounds optimization average establish collected goal according takes appear given
Topic 21: model classification mixture bayesian missing clustering outliers distributions normal variables gives adopted learning treatment inference
Topic 22: modelling developed handle supervised possibility variational having approximation values allow processed scale restrictive focuses introduction
Topic 23: problems graph complexity node step arbitrary graphs algorithm local run providing variant showed labeling checkable
Topic 24: environments parameters technique adaptation speakers deep acoustic neural layer normalization modeling recognition stability wsj called
Topic 25: author applications answered definite multiple line related geotemporal case modelling positive bochner spheres similarly position
Topic 26: algorithms states offer typically presumably update performance failure metastable issue continues risk communication level persistently
Topic 27: time model based study processes computing memory discrete require modelling limit sphere prediction porcu type
Topic 28: propagation susceptibility field equation constructed response mean matching anderson markov diagonal reduced belief ordinary random
Topic 29: new linear cases palmer improved limit adaptive proposed additional structures random robust ordinary method propagation
Topic 30: algorithms ease mechanism forming rapid better fails sparsity issue rule level communication understood continues failure
Topic 31: similarly follows survey raised berg goes characterisation position spheres motivation bochner positive functions obstacle guella
Topic 32: approach popular greedy algorithmic maximization insight modularity limit achieved detection algorithms ease rapid clear quantitative
Topic 33: proposed adaptive additional release information activities limit adapting experimental apply datasets experiments factors improved new
Topic 34: students introduce single particle collision broadly benchmarking simulations jones distribute quasi allows chain open accurate
Topic 35: operators gravitational infty duality explicitly orders supersymmetric dual perturbation applications checked result holds twisted unique

['code pulsedyn nonlinear ulam tsingou toda soliton systems body lennard dynamics specialists pasta integrable accessible',
 'theorem mathbf mathbb polynomial carleson bounded kernel zygmund phases continuous maximal standard operator modulating lies',
 'algebra theory omega koszul shown presented supergravity background branes explicitly orders supersymmetric dual duality gravitational',
 'non numerical obtained fermi decay morse accessible black examine equilibrium recurrence source dynamical distribute quasi',
 'log coloring round pettie number known randomized chung lcl making prove algorithm results recent defective',
 'optimization formalizing modeled bounds average maximizes establish collected total goal given asks takes appear according',
 'question sphere type extensions products extending schoenberg porcu prediction cross survey position similarly goes berg',
 'modelling covariances obstacle geostatistical peron authors menegatto long functions earth guella lines follows berg motivation',
 'carleson mathbb polynomial theorem mathbf bounded truncations extends let operator zygmund modulating lies continuous define',
 'results provides students single introduce simulations particle making benchmarking collision broadly algorithms distribute quasi limit',
 'method ising combining special network concept fields approximate formulate thouless inverse computation approaches structures robust',
 'additional datasets release information activities adapting apply experiments experimental factors channel generates deep speakers adaptation',
 'sqrt chang essentially brandt classic locally defective conjectured ideas upper lemma enlightening frugal vertex relaxed',
 'algorithm graphs local problem lower run providing variant showed checkable labeling solved algorithms making log',
 'perturbation dual supersymmetric duality yau formulated checked calabi determine holds yangian formulation algebraic coupling geometry',
 'degree lll bounded bound best rounds improvement distributed include conjecture list sqrt revelation automatically mathsf',
 'perturbation dual supersymmetric applications result operation unique constants conjectural twisted double stack quantization suggested variable',
 'rewards optimal reward horizon stochastic robot infinite epsilon consider expected nodes finite routing paths generated',
 'paper data fixed large terms arxiv improve infty bounded cases explicitly model orders gravitational operators',
 'models acoustic dynamically dln normalization layer neural generating require introduce limit technique environments parameters adaptation',
 'limit rewards maximizes modeled formalizing bounds optimization average establish collected goal according takes appear given',
 'model classification mixture bayesian missing clustering outliers distributions normal variables gives adopted learning treatment inference',
 'modelling developed handle supervised possibility variational having approximation values allow processed scale restrictive focuses introduction',
 'problems graph complexity node step arbitrary graphs algorithm local run providing variant showed labeling checkable',
 'environments parameters technique adaptation speakers deep acoustic neural layer normalization modeling recognition stability wsj called',
 'author applications answered definite multiple line related geotemporal case modelling positive bochner spheres similarly position',
 'algorithms states offer typically presumably update performance failure metastable issue continues risk communication level persistently',
 'time model based study processes computing memory discrete require modelling limit sphere prediction porcu type',
 'propagation susceptibility field equation constructed response mean matching anderson markov diagonal reduced belief ordinary random',
 'new linear cases palmer improved limit adaptive proposed additional structures random robust ordinary method propagation',
 'algorithms ease mechanism forming rapid better fails sparsity issue rule level communication understood continues failure',
 'similarly follows survey raised berg goes characterisation position spheres motivation bochner positive functions obstacle guella',
 'approach popular greedy algorithmic maximization insight modularity limit achieved detection algorithms ease rapid clear quantitative',
 'proposed adaptive additional release information activities limit adapting experimental apply datasets experiments factors improved new',
 'students introduce single particle collision broadly benchmarking simulations jones distribute quasi allows chain open accurate',
 'operators gravitational infty duality explicitly orders supersymmetric dual perturbation applications checked result holds twisted unique']

In [18]:
fig = best_model.visualize_topic_hierarchy()
fig.show()

C:\Users\zeldan\anaconda3\envs\tfg-topics2\Lib\site-packages\fastopic\_plot.py:265: ClusterWarning:

The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix

In [19]:
df_topics = pd.DataFrame({
    "topic_id":  range(len(best_top_words)),
    "top_words": ["".join(ws) for ws in best_top_words]
})
display(df_topics.head(40))

    topic_id                                          top_words
0          0  code pulsedyn nonlinear ulam tsingou toda soli...
1          1  theorem mathbf mathbb polynomial carleson boun...
2          2  algebra theory omega koszul shown presented su...
3          3  non numerical obtained fermi decay morse acces...
4          4  log coloring round pettie number known randomi...
5          5  optimization formalizing modeled bounds averag...
6          6  question sphere type extensions products exten...
7          7  modelling covariances obstacle geostatistical ...
8          8  carleson mathbb polynomial theorem mathbf boun...
9          9  results provides students single introduce sim...
10        10  method ising combining special network concept...
11        11  additional datasets release information activi...
12        12  sqrt chang essentially brandt classic locally ...
13        13  algorithm graphs local problem lower run provi...
14        14  perturbation dual supersymmetric duality yau f...
15        15  degree lll bounded bound best rounds improveme...
16        16  perturbation dual supersymmetric applications ...
17        17  rewards optimal reward horizon stochastic robo...
18        18  paper data fixed large terms arxiv improve inf...
19        19  models acoustic dynamically dln normalization ...
20        20  limit rewards maximizes modeled formalizing bo...
21        21  model classification mixture bayesian missing ...
22        22  modelling developed handle supervised possibil...
23        23  problems graph complexity node step arbitrary ...
24        24  environments parameters technique adaptation s...
25        25  author applications answered definite multiple...
26        26  algorithms states offer typically presumably u...
27        27  time model based study processes computing mem...
28        28  propagation susceptibility field equation cons...
29        29  new linear cases palmer improved limit adaptiv...
30        30  algorithms ease mechanism forming rapid better...
31        31  similarly follows survey raised berg goes char...
32        32  approach popular greedy algorithmic maximizati...
33        33  proposed adaptive additional release informati...
34        34  students introduce single particle collision b...
35        35  operators gravitational infty duality explicit...

In [20]:
best_model.visualize_topic(top_n=8)