In [1]:

%pip install pandas numpy spacy matplotlib plotly scikit-learn beautifulsoup4 nltk fastopic optuna optuna-dashboard

Requirement already satisfied: pandas in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (2.3.4)
Requirement already satisfied: spacy in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (3.8.7)
Requirement already satisfied: matplotlib in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (3.10.7)
Requirement already satisfied: plotly in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (6.3.1)
Requirement already satisfied: scikit-learn in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (1.7.2)
Requirement already satisfied: beautifulsoup4 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (4.14.2)
Requirement already satisfied: nltk in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (3.9.2)
Requirement already satisfied: fastopic in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (1.0.1)
Requirement already satisfied: optuna in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (4.6.0)
Requirement already satisfied: optuna-dashboard in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (0.20.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (1.0.13)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (2.0.11)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (3.0.10)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (8.3.6)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (2.5.1)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (0.4.1)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (0.20.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (25.0)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from spacy) (3.5.0)
Requirement already satisfied: language-data>=1.2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from langcodes<4.0.0,>=3.2.0->spacy) (1.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.10.5)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.0)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: colorama in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.3.0)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (14.2.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (7.4.1)
Requirement already satisfied: wrapt in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: pillow>=8 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from plotly) (2.9.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from scikit-learn) (1.16.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from beautifulsoup4) (2.8)
Requirement already satisfied: regex>=2021.8.3 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from nltk) (2025.10.23)
Requirement already satisfied: topmost>=1.0.2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from fastopic) (1.0.2)
Requirement already satisfied: alembic>=1.5.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from optuna) (1.17.2)
Requirement already satisfied: colorlog in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from optuna) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from optuna) (2.0.44)
Requirement already satisfied: PyYAML in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from optuna) (6.0.3)
Requirement already satisfied: bottle>=0.13.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from optuna-dashboard) (0.13.4)
Requirement already satisfied: Mako in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: marisa-trie>=1.1.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from language-data>=1.2->langcodes<4.0.0,>=3.2.0->spacy) (1.3.1)
Requirement already satisfied: six>=1.5 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: greenlet>=1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: sentence-transformers>=3.4.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from topmost>=1.0.2->fastopic) (5.1.1)
Requirement already satisfied: torchvision>=0.21.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from topmost>=1.0.2->fastopic) (0.24.0)
Requirement already satisfied: gensim>=4.3.3 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from topmost>=1.0.2->fastopic) (4.4.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (4.57.1)
Requirement already satisfied: torch>=1.11.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (2.9.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (0.35.3)
Requirement already satisfied: filelock in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (3.20.0)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (0.6.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (2025.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from torch>=1.11.0->sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from torch>=1.11.0->sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (3.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=3.4.0->topmost>=1.0.2->fastopic) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\zeldan\anaconda3\envs\tfg-topics2\lib\site-packages (from jinja2->spacy) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:

import random
import re
import time

import matplotlib.pyplot as plt
import numpy as np
import optuna
import pandas as pd
from fastopic import FASTopic
from gensim.corpora import Dictionary
from gensim.models import CoherenceModel
from wordcloud import WordCloud

## FASTopic

In [3]:
# Carga de datos
test = pd.read_csv("data/research-articles/test.csv")
train = pd.read_csv("data/research-articles/train.csv")

display(test.head())
display(train.head())

,ID,TITLE,ABSTRACT
0,20973,Closed-form Marginal Likelihood in Gamma-Poiss...,We present novel understandings of the Gamma...
1,20974,Laboratory mid-IR spectra of equilibrated and ...,Meteorites contain minerals from Solar Syste...
2,20975,Case For Static AMSDU Aggregation in WLANs,Frame aggregation is a mechanism by which mu...
3,20976,The $Gaia$-ESO Survey: the inner disk intermed...,Milky Way open clusters are very diverse in ...
4,20977,Witness-Functions versus Interpretation-Functi...,Proving that a cryptographic protocol is cor...

,ID,TITLE,ABSTRACT,Computer Science,Physics,Mathematics,Statistics,Quantitative Biology,Quantitative Finance
0,1,Reconstructing Subject-Specific Effect Maps,Predictive models allow subject-specific inf...,1,0,0,0,0,0
1,2,Rotation Invariance Neural Network,Rotation invariance and translation invarian...,1,0,0,0,0,0
2,3,Spherical polyharmonics and Poisson kernels fo...,We introduce and develop the notion of spher...,0,0,1,0,0,0
3,4,A finite element approximation for the stochas...,The stochastic Landau--Lifshitz--Gilbert (LL...,0,0,1,0,0,0
4,5,Comparative study of Discrete Wavelet Transfor...,Fourier-transform infra-red (FTIR) spectra o...,1,0,0,1,0,0

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20972 entries, 0 to 20971
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    20972 non-null  int64
 1   TITLE                 20972 non-null  object
 2   ABSTRACT              20972 non-null  object
 3   Computer Science      20972 non-null  int64
 4   Physics               20972 non-null  int64
 5   Mathematics           20972 non-null  int64
 6   Statistics            20972 non-null  int64
 7   Quantitative Biology  20972 non-null  int64
 8   Quantitative Finance  20972 non-null  int64
dtypes: int64(7), object(2)
memory usage: 1.4+ MB

In [5]:
train.dtypes

ID                       int64
TITLE                   object
ABSTRACT                object
Computer Science         int64
Physics                  int64
Mathematics              int64
Statistics               int64
Quantitative Biology     int64
Quantitative Finance     int64
dtype: object

In [24]:
train_small = train.sample(n=10, random_state=42)
documents = list(train_small.ABSTRACT.values)  # utilizaremos solo la columan Abstract como los documentos
print(documents[0])  # como ejemplo imprimimos el primer documento

  Layer normalization is a recently introduced technique for normalizing the
activities of neurons in deep neural networks to improve the training speed and
stability. In this paper, we introduce a new layer normalization technique
called Dynamic Layer Normalization (DLN) for adaptive neural acoustic modeling
in speech recognition. By dynamically generating the scaling and shifting
parameters in layer normalization, DLN adapts neural acoustic models to the
acoustic variability arising from various factors such as speakers, channel
noises, and environments. Unlike other adaptive acoustic models, our proposed
approach does not require additional adaptation data or speaker information
such as i-vectors. Moreover, the model size is fixed as it dynamically
generates adaptation parameters. We apply our proposed DLN to deep
bidirectional LSTM acoustic models and evaluate them on two benchmark datasets
for large vocabulary ASR experiments: WSJ and TED-LIUM release 2. The
experimental results show that our DLN improves neural acoustic models in terms
of transcription accuracy by dynamically adapting to various speakers and
environments.

In [37]:
clean_text = documents
tokenized_texts = [doc.split() for doc in clean_text]
print(tokenized_texts[0])
dictionary = Dictionary(tokenized_texts)
dictionary.filter_extremes(no_below=5, no_above=0.8)

['Layer', 'normalization', 'is', 'a', 'recently', 'introduced', 'technique', 'for', 'normalizing', 'the', 'activities', 'of', 'neurons', 'in', 'deep', 'neural', 'networks', 'to', 'improve', 'the', 'training', 'speed', 'and', 'stability.', 'In', 'this', 'paper,', 'we', 'introduce', 'a', 'new', 'layer', 'normalization', 'technique', 'called', 'Dynamic', 'Layer', 'Normalization', '(DLN)', 'for', 'adaptive', 'neural', 'acoustic', 'modeling', 'in', 'speech', 'recognition.', 'By', 'dynamically', 'generating', 'the', 'scaling', 'and', 'shifting', 'parameters', 'in', 'layer', 'normalization,', 'DLN', 'adapts', 'neural', 'acoustic', 'models', 'to', 'the', 'acoustic', 'variability', 'arising', 'from', 'various', 'factors', 'such', 'as', 'speakers,', 'channel', 'noises,', 'and', 'environments.', 'Unlike', 'other', 'adaptive', 'acoustic', 'models,', 'our', 'proposed', 'approach', 'does', 'not', 'require', 'additional', 'adaptation', 'data', 'or', 'speaker', 'information', 'such', 'as', 'i-vectors.', 'Moreover,', 'the', 'model', 'size', 'is', 'fixed', 'as', 'it', 'dynamically', 'generates', 'adaptation', 'parameters.', 'We', 'apply', 'our', 'proposed', 'DLN', 'to', 'deep', 'bidirectional', 'LSTM', 'acoustic', 'models', 'and', 'evaluate', 'them', 'on', 'two', 'benchmark', 'datasets', 'for', 'large', 'vocabulary', 'ASR', 'experiments:', 'WSJ', 'and', 'TED-LIUM', 'release', '2.', 'The', 'experimental', 'results', 'show', 'that', 'our', 'DLN', 'improves', 'neural', 'acoustic', 'models', 'in', 'terms', 'of', 'transcription', 'accuracy', 'by', 'dynamically', 'adapting', 'to', 'various', 'speakers', 'and', 'environments.']

In [27]:
def coherence_from_topics(topic_words, tokenized_texts, dictionary):
    if not topic_words:
        return -1e6
    try:
        cm = CoherenceModel(topics=topic_words, texts=tokenized_texts, dictionary=dictionary, coherence='c_v')
        return float(cm.get_coherence())
    except Exception as e:
        print("Error coherence:", e)
        return -1e6

In [53]:
def get_top_words(top_words_out, n_words=10):
    normalized_topics = []
    for topic in top_words_out:
        words = []
        for entry in topic:
            # 1) si es tupla (word,score)
            if isinstance(entry, tuple) and len(entry) >= 1:
                candidate = entry[0]
            else:
                candidate = entry

            # 2) si candidate es lista/tupla de caracteres -> unir sin separador
            if isinstance(candidate, (list, tuple)) and all(isinstance(ch, str) and len(ch) == 1 for ch in candidate):
                s = ''.join(candidate)
            # 3) si es string -> usar tal cual
            elif isinstance(candidate, str):
                s = candidate
            else:
                # fallback
                s = str(candidate)

            # 4) limpia y separa en palabras (por espacios)
            #    Puede ser una frase completa, por eso split()
            parts = s.strip().split()
            for p in parts:
                if p:
                    words.append(p)
                if len(words) >= n_words:
                    break
            if len(words) >= n_words:
                break

        # si no se extrajo nada, insertar token vacío para no romper gensim
        if not words:
            words = [""]

        normalized_topics.append(words[:n_words])

    return normalized_topics

In [54]:
def objective(trial):
    """
    Construye un FASTopic con los hiperparámetros sugeridos, entrena (fit_transform)
    y devuelve coherencia c_v (a maximizar).
    """
    # Hiperparámetros a buscar
    n_topics = trial.suggest_int("num_topics", 10, 80)  # rango típico
    DT_alpha = trial.suggest_categorical("DT_alpha", [1.0, 5.0, 10.0, 15.0])
    normalize_embeddings = trial.suggest_categorical("normalize_embeddings", [True, False])
    low_memory = trial.suggest_categorical("low_memory", [False, True])
    learning_rate = trial.suggest_loguniform("learning_rate", 1e-3, 1e-1)
    epochs = trial.suggest_int("epochs", 20, 200)

    # build model (constructor flexible según versión)
    try:
        # FASTopic puede aceptar: FASTopic(num_topics, preprocess=..., doc_embed_model=..., normalize_embeddings=...)
        # Aquí usamos constructor con num_topics y algunos flags; si tu versión tiene firma distinta, se adapta por try/except
        model = FASTopic(num_topics=n_topics,
                         normalize_embeddings=normalize_embeddings,
                         DT_alpha=DT_alpha,
                         low_memory=low_memory,
                         verbose=False)
    except TypeError:
        # fallback: construir sin algunos argumentos
        model = FASTopic(num_topics=n_topics, verbose=False)

    # Entrenar (fit_transform devuelve top_words y doc_topic_dist según README)

    t0 = time.time()
    top_words_out, doc_topic_dist = model.fit_transform(clean_text, learning_rate=learning_rate, epochs=epochs)
    elapsed = time.time() - t0

    # signature diferente: intentar sin lr/epochs

    t0 = time.time()
    top_words_out, doc_topic_dist = model.fit_transform(clean_text)
    elapsed = time.time() - t0

    if len(top_words_out) == 0:
        trial.set_user_attr("n_topics_found", 0)
        return -1e6

    topics_for_gensim = get_top_words(top_words_out)
    print("Top words found:", topics_for_gensim)

    # calcular coherencia c_v
    coh = coherence_from_topics(topics_for_gensim, tokenized_texts, dictionary)

    # guardar attrs útiles
    trial.set_user_attr("elapsed_s", elapsed)
    trial.set_user_attr("n_topics_found", len(top_words))

    return float(coh)

In [55]:
RANDOM_SEED = 42
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
def run_optuna_fastopic(n_trials=20):
    sampler = optuna.samplers.TPESampler(seed=RANDOM_SEED)
    study = optuna.create_study(direction="maximize", sampler=sampler)
    print("Iniciando Optuna para FASTopic. n_trials =", n_trials)
    study.optimize(objective, n_trials=n_trials)
    print("Mejor coherencia:", study.best_value)
    print("Mejores hiperparámetros:", study.best_params)
    return study

In [56]:
study = run_optuna_fastopic(n_trials=20)

[I 2025-12-03 11:53:38,355] A new study created in memory with name: no-name-6cd21de4-b31a-41b5-9c5b-e7149b081481
C:\Users\zeldan\AppData\Local\Temp\ipykernel_15740\3220774820.py:11: FutureWarning:

suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.

Iniciando Optuna para FASTopic. n_trials = 20

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 5003.34it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 9998.34it/s]
C:\Users\zeldan\anaconda3\envs\tfg-topics2\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning:

The parameter 'token_pattern' will not be used since 'tokenizer' is not None'

Training FASTopic: 100%|██████████| 23/23 [00:00<00:00, 28.22it/s]
loading train texts: 100%|██████████| 10/10 [00:00<00:00, 5002.15it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 3987.74it/s]
Training FASTopic: 100%|██████████| 200/200 [00:08<00:00, 24.81it/s]
[I 2025-12-03 11:53:50,925] Trial 0 finished with value: -1000000.0 and parameters: {'num_topics': 36, 'DT_alpha': 1.0, 'normalize_embeddings': True, 'low_memory': False, 'learning_rate': 0.02607024758370768, 'epochs': 23}. Best is trial 0 with value: -1000000.0.

Top words found: ['p r o b l e m s   g r a p h   n o d e   m o d e l   l o w e r   a r b i t r a r y   s t e p   g e n e r a t i n g   n e w   r e q u i r e   b a s e d   l i m i t   r o u t i n g   c o n s i d e r   g e n e r a t e d', 'p r o p o s e d   a p p r o a c h   a d a p t i v e   f i x e d   n e w   i m p r o v e   g e n e r a t i n g   b a s e d   d a t a   l i m i t   m e t h o d   p a p e r   m o d e l   r e q u i r e   t r a i n i n g', 'a l g o r i t h m i c   m o d u l a r i t y   m a x i m i z a t i o n   p o p u l a r   i n s i g h t   p r o v i d e s   g r e e d y   a l g o r i t h m s   s t a t e s   a c h i e v e d   i s s u e   p e r s i s t e n t l y   c o m m u n i t y   u p d a t e   i m p l e m e n t a t i o n', 'a l g o r i t h m i c   m o d u l a r i t y   p o p u l a r   m a x i m i z a t i o n   i n s i g h t   g r e e d y   a l g o r i t h m s   c o m m u n i t y   a c h i e v e d   s t a t e s   p e r s i s t e n t l y   a p a r t   b e t t e r   i m p l e m e n t a t i o n   r u l e', 'k n o w n   l o c a l   n u m b e r   a l g o r i t h m   a l g o r i t h m s   g r a p h s   m a k i n g   p r o v e   p r o b l e m   c o m p l e x i t y   a r b i t r a r y   l o w e r   s t e p   p r o v i d e s   l i m i t', 'a d a p t a t i o n   s p e a k e r s   p a r a m e t e r s   t e c h n i q u e   d e e p   e n v i r o n m e n t s   t r a i n i n g   s t a b i l i t y   l s t m   a d a p t s   v e c t o r s   c h a n n e l   s p e e c h   d y n a m i c   b i d i r e c t i o n a l', 's u s c e p t i b i l i t y   a p p r o x i m a t e   r o b u s t   i s i n g   c o m b i n i n g   t h o u l e s s   a p p r o a c h e s   d i a g o n a l   r e s p o n s e   c o n c e p t   o r d i n a r y   f i e l d s   i n v e r s e   i m p r o v e d   c o n s t r u c t e d', 't i m e   s t u d y   q u e s t i o n   p r o c e s s e s   c o m p u t i n g   v i s i t i n g   a c c o r d i n g   a p p e a r   s t r a t e g y   g i v e n   e s t a b l i s h   a c c u m u l a t e d   m e m o r y   u n i t   a s k s', 'a d a p t a t i o n   s p e a k e r s   p a r a m e t e r s   t e c h n i q u e   d e e p   e n v i r o n m e n t s   e x p e r i m e n t s   d a t a s e t s   i n f o r m a t i o n   n e u r o n s   t r a i n i n g   i m p r o v e s   a d d i t i o n a l   w s j   e v a l u a t e', 'a u t h o r   a p p l i c a t i o n s   i n f t y   o p e r a t o r s   a n a l o g   g e o m e t r y   e n u m e r a t i v e   i d e n t i f i c a t i o n   y a n g i a n   r e s u l t   c l a s s i c a l   c h e c k e d   d i m e n s i o n a l   c e r t a i n   y a u', 's u s c e p t i b i l i t y   m e t h o d   b a s e d   a p p r o x i m a t e   r o b u s t   c o m b i n i n g   i s i n g   a p p r o a c h e s   r e s p o n s e   d i a g o n a l   t h o u l e s s   c o n c e p t   o r d i n a r y   f i e l d s   i n v e r s e', 'r e s u l t s   n u m e r i c a l   a c c e s s i b l e   s o l i t o n   i n t r o d u c e   m a k i n g   p r o g r a m   p r o v i d e s   a c c u r a t e   e n s u r e   p r o v e   s t u d y   c o m p u t i n g   p r o c e s s e s   m o d e l', 'n o n   c o d e   u s e f u l   p u l s e d y n   f i l e   c o l l i s i o n   r i c h   l o c a l i z e d   o p e n   d y n a m i c a l   n o n l i n e a r   i n t e r f a c e   d e s i g n e d   e q u i l i b r i u m   p a r a m e t e r', 'v a r i a b l e   d o u b l e   c o r r e s p o n d e n c e   e x p l i c i t   t w i s t e d   s u g g e s t i o n   c o n j e c t u r a l   s u g g e s t e d   c o u p l i n g   o p e r a t i o n   u n i q u e   c a l a b i   l o o p   p r e s e n t e d   s h o w n', 'm o d e l   d a t a   p a p e r   c l a s s i f i c a t i o n   b a s e d   m e t h o d   m o d e l l i n g   m i x t u r e   o u t l i e r s   m i s s i n g   c l u s t e r i n g   b a y e s i a n   d e v e l o p e d   a p p r o x i m a t i o n   i n f e r e n c e', 'l a r g e   t e r m s   p a p e r   v a r i a b i l i t y   s p e a k e r   m o d e l i n g   s c a l i n g   t e d   a p p l y   n e t w o r k s   b e n c h m a r k   c a l l e d   n o i s e s   s h i f t i n g   e x p e r i m e n t a l', 'c a r l e s o n   m a t h b b   t h e o r e m   m a t h b f   p o l y n o m i a l   k e r n e l   z y g m u n d   l e t   c o n t i n u o u s   m o d u l a t i n g   d e f i n e   t r u n c a t i o n s   e x t e n d s   o p e r a t o r   s t a n d a r d', 'c o m p u t e   p r o p o s e   e n c o d e   p o t e n t i a l   p r o b a b i l i t y   d i s c r e t e   g o a l   b o u n d s   m a x i m i z e   o b j e c t i v e s   a v e r a g e   p r o c e s s   c o l l e c t e d   l o c a t i o n s   e d g e s', 'a c o u s t i c   m o d e l s   d y n a m i c a l l y   n o r m a l i z a t i o n   n e u r a l   d l n   l a y e r   r e q u i r e   i n t r o d u c e   g e n e r a t i n g   i m p r o v e   m o d e l   e n v i r o n m e n t s   d e e p   t e c h n i q u e', 's p h e r e   m o d e l l i n g   q u e s t i o n   s t u d y   m e n e g a t t o   l i n e s   b o c h n e r   s c h o e n b e r g   l o n g   c o v a r i a n c e s   r a i s e d   p r e d i c t i o n   s u r v e y   m o t i v a t i o n   a n s w e r e d', 'c l a s s i f i c a t i o n   c l u s t e r i n g   b a y e s i a n   m i s s i n g   m i x t u r e   o u t l i e r s   h a n d l e   i n t r o d u c t i o n   p o s s i b i l i t y   a l l o w   g i v e s   n o r m a l   v a r i a b l e s   a d o p t e d   v a l u e s', 'r e c e n t   r e l a x e d   l i s t   s i g n i f i c a n t   p r o g r e s s   a u t o m a t i c a l l y   p r o v i d i n g   l a b e l i n g   v a r i a n t   c u r r e n t l y   s o l v i n g   e s s e n t i a l l y   e n l i g h t e n i n g   m a t h s f   u p p e r', 'c l a s s i f i c a t i o n   c l u s t e r i n g   m i s s i n g   b a y e s i a n   m i x t u r e   o u t l i e r s   h a n d l e   i n t r o d u c t i o n   p o s s i b i l i t y   g i v e s   a l l o w   v a r i a b l e s   n o r m a l   r e s t r i c t i v e   a d o p t e d', 'n o n l i n e a r   p u l s e d y n   c o d e   m o r s e   u l a m   s p e c i a l i s t s   i n t e g r a b l e   f e r m i   s y s t e m s   t s i n g o u   d y n a m i c s   t o d a   j o n e s   l e n n a r d   p a s t a', 'o m e g a   e x p l i c i t l y   p e r t u r b a t i o n   s u p e r s y m m e t r i c   o r d e r s   d u a l i t y   g r a v i t a t i o n a l   d u a l   a l g e b r a i c   p r e s e n t a t i o n   d e t e r m i n e   f o r m u l a t i o n   f o r m u l a t e d   q u a n t i z a t i o n   s t a c k', 'o b t a i n e d   a l l o w s   p a r t i c l e   r e c u r r e n c e   a n t i c i p a t e   e a s y   c h a i n   e q u i p a r t i t i o n e d   b l a c k   b e n c h m a r k i n g   s t u d e n t s   e x c i t a t i o n   l i t e r a t u r e   b o x   d i s t r i b u t e', 'a l g e b r a   t h e o r y   k o s z u l   o p e r a t o r s   b a c k g r o u n d   s u p e r g r a v i t y   b r a n e s   s h o w n   p r e s e n t e d   p a p e r   l i n e a r   c a s e s   n o n   l a r g e   t e r m s', 'b o u n d e d   d e g r e e   a r x i v   i m p r o v e   c h e c k a b l e   s o l v e d   s p e d   s h o w e d   r e v e l a t i o n   c o n j e c t u r e d   f r u g a l   b r a n d t   v e r t e x   r u n   c l a s s i c', 'r e w a r d s   o p t i m a l   r e w a r d   s t o c h a s t i c   r o b o t   i n f i n i t e   e p s i l o n   h o r i z o n   f i n i t e   p a t h s   e x p e c t e d   n o d e s   g e n e r a t e d   c o n s i d e r   r o u t i n g', 'l o g   p r o b l e m s   g r a p h s   a l g o r i t h m   c o m p l e x i t y   c o l o r i n g   l l l   r o u n d   p e t t i e   p r o b l e m   s t e p   l o w e r   a r b i t r a r y   g r a p h   n o d e', 'p r o p a g a t i o n   f i e l d   l i n e a r   c a s e s   m e t h o d   m a t c h i n g   a n d e r s o n   s t r u c t u r e s   m a r k o v   b e l i e f   e q u a t i o n   m e a n   p a l m e r   r a n d o m   f o r m u l a t e', 's p h e r e   p o s i t i o n   c r o s s   g e o s t a t i s t i c a l   e x t e n s i o n s   f u n c t i o n s   s i m i l a r l y   s p h e r e s   l i n e   g u e l l a   e a r t h   a u t h o r s   a n s w e r e d   b e r g   s c h o e n b e r g', 's p h e r e   p o s i t i o n   c r o s s   g e o s t a t i s t i c a l   e x t e n s i o n s   f u n c t i o n s   s i m i l a r l y   s p h e r e s   b e r g   g u e l l a   a u t h o r s   l i n e   e a r t h   a n s w e r e d   o b s t a c l e', 'n o n l i n e a r   p u l s e d y n   c o d e   s y s t e m s   u l a m   f e r m i   m o r s e   i n t e g r a b l e   t o d a   s p e c i a l i s t s   d y n a m i c s   j o n e s   l e n n a r d   p a s t a   b o d y', 'g r e e d y   a l g o r i t h m i c   m o d u l a r i t y   p o p u l a r   m a x i m i z a t i o n   i n s i g h t   a l g o r i t h m s   l i m i t   c o m m u n i t y   a p a r t   p e r s i s t e n t l y   a c h i e v e d   s t a t e s   b e t t e r   r u l e', 'c h u n g   l c l   r a n d o m i z e d   s q r t   p e t t i e   i m p r o v e m e n t   i n c l u d e   c h a n g   r o u n d s   b o u n d   d i s t r i b u t e d   b e s t   r o u n d   l l l   c o l o r i n g']
Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 4993.81it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 10007.88it/s]
Training FASTopic: 100%|██████████| 45/45 [00:02<00:00, 18.14it/s]
loading train texts: 100%|██████████| 10/10 [00:00<00:00, 4992.03it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 10003.11it/s]
Training FASTopic: 100%|██████████| 200/200 [00:12<00:00, 16.15it/s]
[I 2025-12-03 11:54:09,400] Trial 1 finished with value: -1000000.0 and parameters: {'num_topics': 78, 'DT_alpha': 1.0, 'normalize_embeddings': False, 'low_memory': False, 'learning_rate': 0.01673808578875214, 'epochs': 45}. Best is trial 0 with value: -1000000.0.
[W 2025-12-03 11:54:09,402] Trial 2 failed with parameters: {'num_topics': 30, 'DT_alpha': 10.0, 'normalize_embeddings': False, 'low_memory': True, 'learning_rate': 0.002193048555664369, 'epochs': 31} because of the following error: AssertionError().
Traceback (most recent call last):
  File "C:\Users\zeldan\anaconda3\envs\tfg-topics2\Lib\site-packages\optuna\study\_optimize.py", line 205, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "C:\Users\zeldan\AppData\Local\Temp\ipykernel_15740\3220774820.py", line 30, in objective
    top_words_out, doc_topic_dist = model.fit_transform(clean_text, learning_rate=learning_rate, epochs=epochs)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zeldan\anaconda3\envs\tfg-topics2\Lib\site-packages\fastopic\FASTopic.py", line 125, in fit_transform
    assert self.low_memory_batch_size is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
[W 2025-12-03 11:54:09,402] Trial 2 failed with value None.

Top words found: ['c o l o r i n g   p e t t i e   r a n d o m i z e d   l c l   s q r t   c h u n g   r o u n d   l l l   l o g   b o u n d   i m p r o v e m e n t   i n c l u d e   c h a n g   r o u n d s   d i s t r i b u t e d', 'd a t a   p a p e r   c l a s s i f i c a t i o n   o u t l i e r s   c l u s t e r i n g   b a y e s i a n   m i x t u r e   m i s s i n g   v a r i a b l e s   l a t e n t   h a n d l e   i n f e r e n c e   p o s s i b i l i t y   i n t r o d u c t i o n   s u p e r v i s e d', 'a l g e b r a   k o s z u l   t h e o r y   b a c k g r o u n d   s u p e r g r a v i t y   p r e s e n t e d   s h o w n   d u a l   e x p l i c i t l y   p e r t u r b a t i o n   g r a v i t a t i o n a l   s u p e r s y m m e t r i c   d u a l i t y   o r d e r s   a u t h o r', 'c o d e   p u l s e d y n   n o n l i n e a r   m o r s e   j o n e s   s o l i t o n   b o d y   i n t e g r a b l e   t s i n g o u   l e n n a r d   f e r m i   p a s t a   d y n a m i c s   s p e c i a l i s t s   u l a m', 'o m e g a   b r a n e s   o p e r a t o r s   a r x i v   l i m i t   s h o w n   a l g e b r a   t h e o r y   k o s z u l   a u t h o r   p r e s e n t e d   a p p l i c a t i o n s   b a c k g r o u n d   s u p e r g r a v i t y   d u a l', 's p h e r e   s i m i l a r l y   c h a r a c t e r i s a t i o n   g o e s   p r o d u c t s   p o s i t i o n   e x t e n d i n g   r e l a t e d   m e n e g a t t o   c o v a r i a n c e s   b e r g   p e r o n   m o t i v a t i o n   a n s w e r e d   w e a t h e r', 'm o d e l s   a d a p t i v e   p r o p o s e d   n e w   i n t r o d u c e   m e t h o d   p r o p a g a t i o n   a p p r o a c h   f i e l d   i m p r o v e   a c o u s t i c   d l n   n o r m a l i z a t i o n   l a y e r   n e u r a l', 'r e s u l t s   n o n   k n o w n   m a k i n g   p r o v e   t h e o r y   a p p l i c a t i o n s   a u t h o r   i n t r o d u c e   i m p r o v e   a p p r o a c h   l i m i t   s t u d y   t i m e   p r o p o s e d', 'l o g   l l l   r o u n d   p e t t i e   c o l o r i n g   c h u n g   s q r t   l c l   r a n d o m i z e d   d e g r e e   b e s t   d i s t r i b u t e d   c h a n g   r o u n d s   i n c l u d e', 'm a t h b b   m a t h b f   c a r l e s o n   t h e o r e m   p o l y n o m i a l   l e t   k e r n e l   c o n t i n u o u s   o p e r a t o r   m a x i m a l   d e f i n e   s t a n d a r d   l i e s   z y g m u n d   t r u n c a t i o n s', 'c o l o r i n g   r a n d o m i z e d   b o u n d   i m p r o v e m e n t   i n c l u d e   v a r i a n t   c h a n g   c h e c k a b l e   r o u n d s   d i s t r i b u t e d   l c l   e s s e n t i a l l y   b e s t   r e l a x e d   p e t t i e', 't e r m s   l a r g e   f i x e d   p a p e r   o p e r a t o r s   i n f t y   l i n e a r   c a s e s   l i m i t   a p p l i c a t i o n s   a u t h o r   i m p r o v e   a p p r o a c h   t h e o r y   d a t a', 'c a s e s   l i n e a r   s u s c e p t i b i l i t y   a p p r o x i m a t e   r e d u c e d   c o n c e p t   r e s p o n s e   n e t w o r k   m a r k o v   c o m b i n i n g   b e l i e f   t h o u l e s s   c o n s t r u c t e d   m e a n   i m p r o v e d', 'p r o p a g a t i o n   s u s c e p t i b i l i t y   m e t h o d   f i e l d   i n v e r s e   s t r u c t u r e s   a n d e r s o n   c o m p u t a t i o n   r a n d o m   e q u a t i o n   a p p r o a c h e s   r o b u s t   f o r m u l a t e   m a t c h i n g   p a l m e r', 'm a t h b b   m a t h b f   c a r l e s o n   t h e o r e m   p o l y n o m i a l   l e t   k e r n e l   c o n t i n u o u s   o p e r a t o r   m a x i m a l   s t a n d a r d   d e f i n e   z y g m u n d   l i e s   t r u n c a t i o n s', 'p r o v i d e s   p r o g r a m   e n s u r e   s t a t e   b r o a d l y   i i i   u s e f u l   p a r t i c l e   f i l e   t r a n s p a r e n c y   e x c i t a t i o n   a l l o w s   s o u r c e   a n t i c i p a t e   e x a m i n e', 's p h e r e   s i m i l a r l y   c h a r a c t e r i s a t i o n   g o e s   p r o d u c t s   e x t e n d i n g   p o s i t i o n   r e l a t e d   m e n e g a t t o   c o v a r i a n c e s   b e r g   p e r o n   m o t i v a t i o n   a n s w e r e d   w e a t h e r', 'l o c a l   n u m b e r   a l g o r i t h m s   a l g o r i t h m   g r a p h s   p r o b l e m s   k n o w n   l i m i t   i m p r o v e   m a k i n g   p r o v e   a r x i v   a p p r o a c h   d e g r e e   l o g', 'i n f t y   o p e r a t o r s   c a s e s   l i n e a r   a u t h o r   a p p l i c a t i o n s   l i m i t   s h o w n   t h e o r y   b r a n e s   a l g e b r a   k o s z u l   o m e g a   p r e s e n t e d   a r x i v', 's u s c e p t i b i l i t y   m e t h o d   a p p r o x i m a t e   r e d u c e d   c o n c e p t   n e t w o r k   r e s p o n s e   m a r k o v   c o m b i n i n g   b e l i e f   t h o u l e s s   c o n s t r u c t e d   m e a n   i m p r o v e d   o r d i n a r y', 'p r o p a g a t i o n   f i e l d   n o n l i n e a r   p u l s e d y n   c o d e   s y s t e m s   t o d a   a c c e s s i b l e   u l a m   i n t r o d u c e   s p e c i a l i s t s   d y n a m i c s   p a s t a   f e r m i   l e n n a r d', 'm o d u l a r i t y   g r e e d y   m a x i m i z a t i o n   p o p u l a r   i n s i g h t   a l g o r i t h m i c   c o m m u n i c a t i o n   c l e a r   m e t a s t a b l e   e a s e   r u l e   b e t t e r   i s s u e   p e r s i s t e n t l y   o f f e r', 's p h e r e   s i m i l a r l y   c h a r a c t e r i s a t i o n   g o e s   p r o d u c t s   p o s i t i o n   e x t e n d i n g   r e l a t e d   m e n e g a t t o   c o v a r i a n c e s   b e r g   p e r o n   m o t i v a t i o n   a n s w e r e d   w e a t h e r', 'o r d e r s   d u a l i t y   s u p e r s y m m e t r i c   g r a v i t a t i o n a l   p e r t u r b a t i o n   e x p l i c i t l y   d u a l   k o s z u l   t h r e e f o l d s   e n u m e r a t i v e   a d s   c o u p l i n g   c o n s t a n t s   c a l a b i   f o r m', 's p e a k e r s   e n v i r o n m e n t s   a d a p t a t i o n   d e e p   p a r a m e t e r s   t e c h n i q u e   d l n   n o r m a l i z a t i o n   l a y e r   n e u r a l   a c o u s t i c   l s t m   g e n e r a t e s   s t a b i l i t y   s p e e c h', 's p e a k e r s   e n v i r o n m e n t s   a d a p t a t i o n   d e e p   p a r a m e t e r s   t e c h n i q u e   d l n   n o r m a l i z a t i o n   l a y e r   n e u r a l   a c o u s t i c   l s t m   g e n e r a t e s   s t a b i l i t y   n o r m a l i z i n g', 'k n o w n   m a k i n g   p r o v e   c o l o r i n g   p e t t i e   l o g   r o u n d   l l l   c h u n g   s q r t   r a n d o m i z e d   l c l   d e g r e e   r o u n d s   b e s t', 'o r d e r s   d u a l i t y   s u p e r s y m m e t r i c   g r a v i t a t i o n a l   p e r t u r b a t i o n   e x p l i c i t l y   d u a l   k o s z u l   t h r e e f o l d s   e n u m e r a t i v e   a d s   c o u p l i n g   c o n s t a n t s   c a l a b i   f o r m', 's p e a k e r s   e n v i r o n m e n t s   a d a p t a t i o n   d e e p   p a r a m e t e r s   t e c h n i q u e   d l n   n o r m a l i z a t i o n   l a y e r   n e u r a l   l s t m   g e n e r a t e s   s t a b i l i t y   n o r m a l i z i n g   s p e e c h', 'c o d e   p u l s e d y n   n o n l i n e a r   m o r s e   j o n e s   s o l i t o n   b o d y   i n t e g r a b l e   t s i n g o u   l e n n a r d   f e r m i   p a s t a   d y n a m i c s   s p e c i a l i s t s   u l a m', 'r e w a r d s   o p t i m a l   r e w a r d   m a x i m i z e s   f o r m a l i z i n g   b o u n d s   p r o b a b i l i t y   l o c a t i o n s   s t r a t e g i e s   t o t a l   t r a v e l i n g   e n c o d e   e x i s t i n g   d i s a p p e a r s   m e m o r y', 't h e o r y   p u l s e d y n   n o n l i n e a r   c o d e   m a k i n g   p r o v e   k n o w n   s y s t e m s   t o d a   u l a m   a c c e s s i b l e   s p e c i a l i s t s   d y n a m i c s   p a s t a   f e r m i', 'c l a s s i f i c a t i o n   m i x t u r e   c l u s t e r i n g   b a y e s i a n   m i s s i n g   o u t l i e r s   v a l u e s   s e n s i t i v i t y   r e s t r i c t i v e   a p p r o x i m a t i o n   h a n d l e   s c a l e   p o s s i b i l i t y   i n f e r e n c e   s u p e r v i s e d', 'r e w a r d s   m a x i m i z e s   f o r m a l i z i n g   o p t i m a l   b o u n d s   p r o b a b i l i t y   l o c a t i o n s   s t r a t e g i e s   t o t a l   t r a v e l i n g   r e w a r d   e n c o d e   e x i s t i n g   a c c u m u l a t e d   d i s t a n c e', 't i m e   s t u d y   q u e s t i o n   p r o c e s s e s   c o m p u t i n g   s p h e r e   s i m i l a r l y   c h a r a c t e r i s a t i o n   l i n e s   m e n e g a t t o   c o v a r i a n c e s   a u t h o r s   s c h o e n b e r g   p r o d u c t s   g o e s', 'c o m p l e x i t y   a r b i t r a r y   s t e p   l o w e r   p r o b l e m   g r a p h   n o d e   c o l o r i n g   r a n d o m i z e d   p e t t i e   i m p r o v e   l c l   s q r t   c h u n g   b o u n d', 'c o d e   p u l s e d y n   n o n l i n e a r   m o r s e   j o n e s   s o l i t o n   b o d y   i n t e g r a b l e   t s i n g o u   l e n n a r d   f e r m i   p a s t a   d y n a m i c s   s p e c i a l i s t s   u l a m', 'm o d u l a r i t y   g r e e d y   m a x i m i z a t i o n   p o p u l a r   i n s i g h t   a l g o r i t h m i c   a l g o r i t h m s   c o m m u n i c a t i o n   c l e a r   m e t a s t a b l e   e a s e   r u l e   b e t t e r   i s s u e   p e r s i s t e n t l y', 's p e a k e r s   e n v i r o n m e n t s   a d a p t a t i o n   d e e p   p a r a m e t e r s   t e c h n i q u e   d l n   n o r m a l i z a t i o n   l a y e r   n e u r a l   a c o u s t i c   l s t m   g e n e r a t e s   s t a b i l i t y   n o r m a l i z i n g', 'p r o c e s s e s   c o m p u t i n g   s t u d y   t i m e   n u m e r i c a l   n o n l i n e a r   c o d e   p u l s e d y n   u l a m   a c c e s s i b l e   s y s t e m s   t o d a   s p e c i a l i s t s   d y n a m i c s   p a s t a', 'v a r i a n t   c h e c k a b l e   e s s e n t i a l l y   r e l a x e d   i d e a s   b r a n d t   f r u g a l   a u t o m a t i c a l l y   p r o g r e s s   r u n   s o l v i n g   c o n j e c t u r e   c u r r e n t l y   c l a s s i c   c o n j e c t u r e d', 'c l a s s i f i c a t i o n   m i x t u r e   c l u s t e r i n g   b a y e s i a n   m i s s i n g   o u t l i e r s   v a l u e s   s e n s i t i v i t y   r e s t r i c t i v e   a p p r o x i m a t i o n   h a n d l e   s c a l e   p o s s i b i l i t y   i n f e r e n c e   s u p e r v i s e d', 's p e a k e r s   a d a p t a t i o n   e n v i r o n m e n t s   p a r a m e t e r s   d e e p   t e c h n i q u e   d l n   n o r m a l i z a t i o n   a c o u s t i c   l a y e r   n e u r a l   a p p r o a c h   l s t m   g e n e r a t e s   s t a b i l i t y', 'o r d e r s   d u a l i t y   s u p e r s y m m e t r i c   g r a v i t a t i o n a l   p e r t u r b a t i o n   e x p l i c i t l y   d u a l   k o s z u l   t h r e e f o l d s   e n u m e r a t i v e   a d s   c o u p l i n g   c o n s t a n t s   c a l a b i   f o r m', 'r e w a r d s   o p t i m a l   r e w a r d   m a x i m i z e s   f o r m a l i z i n g   b o u n d s   p r o b a b i l i t y   l o c a t i o n s   s t r a t e g i e s   t o t a l   t r a v e l i n g   e n c o d e   e x i s t i n g   a c c u m u l a t e d   d i s t a n c e', 'm a t h b b   m a t h b f   c a r l e s o n   t h e o r e m   p o l y n o m i a l   l e t   k e r n e l   c o n t i n u o u s   o p e r a t o r   m a x i m a l   s t a n d a r d   d e f i n e   z y g m u n d   l i e s   t r u n c a t i o n s', 'c l a s s i f i c a t i o n   m i x t u r e   c l u s t e r i n g   b a y e s i a n   m i s s i n g   o u t l i e r s   v a l u e s   s e n s i t i v i t y   r e s t r i c t i v e   a p p r o x i m a t i o n   h a n d l e   s c a l e   p o s s i b i l i t y   i n f e r e n c e   s u p e r v i s e d', 'm o d e l l i n g   v a r i a t i o n a l   h a v i n g   a l l o w   d e v e l o p e d   v a l u e s   c l a s s i f i c a t i o n   m i x t u r e   m i s s i n g   c l u s t e r i n g   b a y e s i a n   o u t l i e r s   r e s t r i c t i v e   l e a r n i n g   p o s s i b i l i t y', 'a l g e b r a   k o s z u l   p r e s e n t e d   o r d e r s   d u a l i t y   s u p e r s y m m e t r i c   g r a v i t a t i o n a l   p e r t u r b a t i o n   e x p l i c i t l y   d u a l   s u p e r g r a v i t y   b a c k g r o u n d   s h o w n   c e r t a i n   d e t e r m i n e', 'm o d e l   b a s e d   m e t h o d   n e w   c l a s s i f i c a t i o n   d a t a   c l u s t e r i n g   m i x t u r e   b a y e s i a n   m i s s i n g   o u t l i e r s   l a t e n t   p o s s i b i l i t y   h a n d l e   s u p e r v i s e d', 'a p p r o a c h   p r o p o s e d   a l g o r i t h m i c   i n s i g h t   p o p u l a r   m a x i m i z a t i o n   g r e e d y   m o d u l a r i t y   a l g o r i t h m s   e s t i m a t i n g   f a i l u r e   u p d a t e   r a p i d   q u a n t i t a t i v e   l e v e l', 'r e w a r d s   m a x i m i z e s   o p t i m a l   r e w a r d   f o r m a l i z i n g   b o u n d s   p r o b a b i l i t y   l o c a t i o n s   s t r a t e g i e s   t o t a l   t r a v e l i n g   e n c o d e   e x i s t i n g   a c c u m u l a t e d   m e m o r y', 'v a r i a n t   c h e c k a b l e   e s s e n t i a l l y   r e l a x e d   i d e a s   b r a n d t   f r u g a l   a u t o m a t i c a l l y   p r o g r e s s   r u n   s o l v i n g   c o n j e c t u r e   c u r r e n t l y   c l a s s i c   c o n j e c t u r e d', 'g r a p h   n o d e   p r o b l e m s   l o w e r   a r b i t r a r y   s t e p   p r o b l e m   c o m p l e x i t y   l i m i t   g r a p h s   a l g o r i t h m   r e w a r d s   o p t i m a l   r e w a r d   e p s i l o n', 'm o d u l a r i t y   g r e e d y   m a x i m i z a t i o n   p o p u l a r   i n s i g h t   a l g o r i t h m i c   c o m m u n i c a t i o n   c l e a r   m e t a s t a b l e   e a s e   r u l e   b e t t e r   i s s u e   p e r s i s t e n t l y   o f f e r', 'r e w a r d s   r e w a r d   o p t i m a l   h o r i z o n   s t o c h a s t i c   e p s i l o n   r o b o t   i n f i n i t e   f i n i t e   e x p e c t e d   c o n s i d e r   g e n e r a t e d   p a t h s   r o u t i n g   n o d e s', 'm o d u l a r i t y   g r e e d y   m a x i m i z a t i o n   p o p u l a r   i n s i g h t   a l g o r i t h m i c   c o m m u n i c a t i o n   c l e a r   m e t a s t a b l e   e a s e   r u l e   b e t t e r   i s s u e   p e r s i s t e n t l y   o f f e r', 's p e a k e r s   e n v i r o n m e n t s   a d a p t a t i o n   d e e p   p a r a m e t e r s   t e c h n i q u e   d l n   n o r m a l i z a t i o n   l a y e r   n e u r a l   l s t m   g e n e r a t e s   s t a b i l i t y   n o r m a l i z i n g   s p e e c h', 's p h e r e   s i m i l a r l y   c h a r a c t e r i s a t i o n   g o e s   p r o d u c t s   e x t e n d i n g   p o s i t i o n   r e l a t e d   m e n e g a t t o   c o v a r i a n c e s   b e r g   p e r o n   m o t i v a t i o n   a n s w e r e d   w e a t h e r', 'l i m i t   a l g o r i t h m s   a l g o r i t h m i c   i n s i g h t   p o p u l a r   m a x i m i z a t i o n   g r e e d y   m o d u l a r i t y   e s t i m a t i n g   f a i l u r e   u p d a t e   r a p i d   l e v e l   q u a n t i t a t i v e   f a i l s', 'a u t h o r   a p p l i c a t i o n s   s p h e r e   s i m i l a r l y   c h a r a c t e r i s a t i o n   p r o d u c t s   r e l a t e d   e x t e n d i n g   p o s i t i o n   g o e s   m e n e g a t t o   a n s w e r e d   b e r g   p e r o n   s p h e r e s', 's u s c e p t i b i l i t y   m e t h o d   a p p r o x i m a t e   r e d u c e d   c o n c e p t   n e t w o r k   r e s p o n s e   m a r k o v   c o m b i n i n g   b e l i e f   t h o u l e s s   c o n s t r u c t e d   m e a n   i m p r o v e d   o r d i n a r y', 'r e w a r d s   m a x i m i z e s   o p t i m a l   r e w a r d   f o r m a l i z i n g   b o u n d s   p r o b a b i l i t y   l o c a t i o n s   s t r a t e g i e s   t o t a l   t r a v e l i n g   e n c o d e   e x i s t i n g   a c c u m u l a t e d   d i s a p p e a r s', 'd y n a m i c a l l y   r e q u i r e   g e n e r a t i n g   n e w   i m p r o v e   a p p r o a c h   p r o p o s e d   a c o u s t i c   d l n   n o r m a l i z a t i o n   n e u r a l   l a y e r   t e c h n i q u e   s p e a k e r s   p a r a m e t e r s', 'a c o u s t i c   n e u r a l   l a y e r   n o r m a l i z a t i o n   d l n   i m p r o v e   a p p r o a c h   t e c h n i q u e   p a r a m e t e r s   d e e p   a d a p t a t i o n   e n v i r o n m e n t s   s p e a k e r s   a d a p t s   s c a l i n g', 'p r o b l e m s   g r a p h s   a l g o r i t h m   c o m p l e x i t y   p r o b l e m   s t e p   a r b i t r a r y   l o w e r   n o d e   g r a p h   l i m i t   i m p r o v e   p r o v e   m a k i n g   k n o w n', 'c o d e   p u l s e d y n   n o n l i n e a r   m o r s e   j o n e s   s o l i t o n   b o d y   i n t e g r a b l e   t s i n g o u   l e n n a r d   f e r m i   p a s t a   d y n a m i c s   s p e c i a l i s t s   u l a m', 'o r d e r s   d u a l i t y   s u p e r s y m m e t r i c   g r a v i t a t i o n a l   p e r t u r b a t i o n   e x p l i c i t l y   d u a l   t h r e e f o l d s   e n u m e r a t i v e   a d s   k o s z u l   c o u p l i n g   c o n s t a n t s   c a l a b i   f o r m', 's p h e r e   s i m i l a r l y   c h a r a c t e r i s a t i o n   g o e s   p r o d u c t s   p o s i t i o n   e x t e n d i n g   r e l a t e d   m e n e g a t t o   c o v a r i a n c e s   b e r g   p e r o n   m o t i v a t i o n   a n s w e r e d   w e a t h e r', 'r e w a r d s   r e w a r d   o p t i m a l   t i m e   h o r i z o n   s t o c h a s t i c   e p s i l o n   r o b o t   i n f i n i t e   p r o c e s s e s   c o m p u t i n g   f i n i t e   e x p e c t e d   c o n s i d e r   g e n e r a t e d', 'c o d e   p u l s e d y n   n o n l i n e a r   m o r s e   j o n e s   s o l i t o n   b o d y   i n t e g r a b l e   t s i n g o u   l e n n a r d   f e r m i   p a s t a   d y n a m i c s   s p e c i a l i s t s   u l a m', 'r e w a r d s   r e w a r d   o p t i m a l   h o r i z o n   s t o c h a s t i c   e p s i l o n   r o b o t   i n f i n i t e   f i n i t e   e x p e c t e d   c o n s i d e r   g e n e r a t e d   p a t h s   r o u t i n g   n o d e s', 'b o u n d e d   d e g r e e   a r x i v   m a t h b f   c a r l e s o n   m a t h b b   t h e o r e m   p o l y n o m i a l   k n o w n   m a k i n g   p r o v e   l e t   e x t e n d s   o p e r a t o r   k e r n e l', 'n u m e r i c a l   o b t a i n e d   s t u d y   t i m e   a p p l i c a t i o n s   a u t h o r   c a r l e s o n   m a t h b f   m a t h b b   t h e o r e m   p o l y n o m i a l   k n o w n   l i e s   z y g m u n d   t r u n c a t i o n s', 'c o d e   p u l s e d y n   n o n l i n e a r   m o r s e   j o n e s   s o l i t o n   b o d y   i n t e g r a b l e   t s i n g o u   l e n n a r d   f e r m i   p a s t a   d y n a m i c s   s p e c i a l i s t s   u l a m', 's u s c e p t i b i l i t y   m e t h o d   a p p r o x i m a t e   r e d u c e d   c o n c e p t   n e t w o r k   r e s p o n s e   m a r k o v   c o m b i n i n g   b e l i e f   t h o u l e s s   c o n s t r u c t e d   m e a n   i m p r o v e d   o r d i n a r y', 'c l a s s i f i c a t i o n   m i x t u r e   c l u s t e r i n g   b a y e s i a n   m i s s i n g   o u t l i e r s   v a l u e s   s e n s i t i v i t y   r e s t r i c t i v e   a p p r o x i m a t i o n   h a n d l e   s c a l e   p o s s i b i l i t y   i n f e r e n c e   s u p e r v i s e d', 'a l g e b r a   t h e o r y   k o s z u l   b a c k g r o u n d   s u p e r g r a v i t y   s h o w n   p r e s e n t e d   d u a l   e x p l i c i t l y   p e r t 

AssertionError:

In [31]:

# ========== Reentrenar el mejor modelo con los mejores hiperparámetros ==========
best = study.best_params
print("Reentrenando FASTopic con:", best)

# Intentar crear modelo con esos parámetros

best_model = FASTopic(num_topics=best["num_topics"],
                      normalize_embeddings=best.get("normalize_embeddings", True),
                      DT_alpha=best.get("DT_alpha", 5.0),
                      low_memory=best.get("low_memory", False),
                      device=best.get("device", "cpu"),
                      verbose=True)


# Fit final (intentar con lr/epochs)

best_top_words, best_doc_topic_dist = best_model.fit_transform(clean_text, learning_rate=best.get("learning_rate", 0.01), epochs=best.get("epochs", 100))

[I 2025-12-03 11:31:41,432] A new study created in memory with name: no-name-e150bcbe-393f-4732-8b84-420130c8960f

Iniciando Optuna para FASTopic. n_trials = 20

C:\Users\zeldan\AppData\Local\Temp\ipykernel_15740\3436640344.py:11: FutureWarning:

suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 9993.58it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 9991.20it/s]
C:\Users\zeldan\anaconda3\envs\tfg-topics2\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning:

The parameter 'token_pattern' will not be used since 'tokenizer' is not None'

Training FASTopic: 100%|██████████| 23/23 [00:00<00:00, 30.57it/s]
loading train texts: 100%|██████████| 10/10 [00:00<00:00, 10010.27it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 10019.84it/s]
Training FASTopic: 100%|██████████| 200/200 [00:06<00:00, 31.55it/s]
[I 2025-12-03 11:31:52,088] Trial 0 finished with value: -1000000.0 and parameters: {'num_topics': 36, 'DT_alpha': 1.0, 'normalize_embeddings': True, 'low_memory': False, 'learning_rate': 0.02607024758370768, 'epochs': 23}. Best is trial 0 with value: -1000000.0.

Error coherence: unable to interpret topic as either a list of tokens or a list of ids

loading train texts: 100%|██████████| 10/10 [00:00<00:00, 5003.94it/s]
parsing texts: 100%|██████████| 10/10 [00:00<?, ?it/s]
Training FASTopic: 100%|██████████| 45/45 [00:01<00:00, 26.15it/s]
loading train texts: 100%|██████████| 10/10 [00:00<00:00, 10022.23it/s]
parsing texts: 100%|██████████| 10/10 [00:00<00:00, 10017.44it/s]
Training FASTopic: 100%|██████████| 200/200 [00:09<00:00, 20.81it/s]
[I 2025-12-03 11:32:06,860] Trial 1 finished with value: -1000000.0 and parameters: {'num_topics': 78, 'DT_alpha': 1.0, 'normalize_embeddings': False, 'low_memory': False, 'learning_rate': 0.01673808578875214, 'epochs': 45}. Best is trial 0 with value: -1000000.0.
[W 2025-12-03 11:32:06,862] Trial 2 failed with parameters: {'num_topics': 30, 'DT_alpha': 10.0, 'normalize_embeddings': False, 'low_memory': True, 'learning_rate': 0.002193048555664369, 'epochs': 31} because of the following error: AssertionError().
Traceback (most recent call last):
  File "C:\Users\zeldan\anaconda3\envs\tfg-topics2\Lib\site-packages\optuna\study\_optimize.py", line 205, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "C:\Users\zeldan\AppData\Local\Temp\ipykernel_15740\3436640344.py", line 30, in objective
    top_words_out, doc_topic_dist = model.fit_transform(clean_text, learning_rate=learning_rate, epochs=epochs)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zeldan\anaconda3\envs\tfg-topics2\Lib\site-packages\fastopic\FASTopic.py", line 125, in fit_transform
    assert self.low_memory_batch_size is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
[W 2025-12-03 11:32:06,863] Trial 2 failed with value None.

Error coherence: unable to interpret topic as either a list of tokens or a list of ids

AssertionError:

In [42]:
best_model.get_top_words()

Topic 0: magnetic phase spin states range temperature orders coupling strong weak critical length transition mode nearest
Topic 1: support needed established protocol years path challenges internet issue plays multiplex lce secure exploits codeword
Topic 2: model models order distribution density parameters proposed process noise error compared standard mean probability rate
Topic 3: able frames flow games motion action potentially robot sensor shape environment robots super parallel environments
Topic 4: quantum frequency spectrum response experimentally measurement account experiment frequencies exciton freedom pulse damping appropriate phonon
Topic 5: study field systems large different dimensional properties energy small obtained interactions observed including type like
Topic 6: control range contrast stability evolutionary perspective principles pair drift takes vehicle kinetic theoretic intrinsic utility
Topic 7: approximation samples bayesian inference setting estimation kernel convergence guarantees signals negative sensing inverse semi variational
Topic 8: simple force background physical need discussed kind moving transmission shell anomalous security relationship majority solid
Topic 9: information level multi code stochastic language better strategy examples key optimization paths search open furthermore
Topic 10: theory operators omega chain existence algebra algebras described factor gives evolution characterize formulate lie integral
Topic 11: discuss variety loop fluid forcing understood tools emitter utilized author induces culture passivity freely magnetized
Topic 12: matrix set estimates bounds convex coefficients special property geometric polynomial asymptotic volume geometry relative norm
Topic 13: performance data classification source domain training image improve art machine input dataset generative target accuracy
Topic 14: high state present low demonstrate experiments single techniques times end effective significant recently way finally
Topic 15: evidence neutron sufficiently acceleration disks produced conclusion vertical substantial blue metal electric sites principal spirals
Topic 16: results paper method methods new non use work space number provide function given linear case
Topic 17: exchange vanishing absence excitations vortex responsible crossed antiferromagnet antiferromagnetic doping afm plumbene neighbor magnetization nontrivial
Topic 18: mathcal general equation interesting equivalent employing position polynomials asymptotically price formed scalar taken complement verified
Topic 19: learning approach based propose neural framework deep novel knowledge existing feature approaches learn prediction representation
Topic 20: network networks random real complex datasets proposed nodes sampling community measures node measure focus true
Topic 21: solar planets self place stable disk conflict unified planet hot ones concerned giant rise polarized
Topic 22: communities propagation technique relevant artificial face estimating rates virtual normal researchers increasingly metrics schemes risk
Topic 23: surface discrete channel equations matrices fixed partial covariance quaternion weighted estimators invariant difference estimator imaging
Topic 24: experimental social lattice question understanding dynamics define delta analytical varying cross individuals connection groups perfect
Topic 25: mass formation cluster line star matter lambda galaxy sigma galaxies dark light emission sim gravitational
Topic 26: data time based applications features power detection multiple resolution series measurements available provides observations processing
Topic 27: software requirements unique modern contract meet extends lipschitz old regularity exponent specifications contracts networking engineers
Topic 28: example operator elements tau classes compact general regular notion consequence element closed necessary preferences introducing
Topic 29: thermal plane magnitude ray pressure combined conventional electronic bulk plasma observational overall material atoms theoretically
Topic 30: terms particular common positive selection transform protocols constructed euclidean fourier build symplectic sphere arise structures
Topic 31: design convolutional loss manifolds string capacity explicitly improves outliers avoiding switch start contains implement cup
Topic 32: analysis scale test research user identify context specific events users content management increase items consists
Topic 33: global term simulated considering multidimensional relation bifacial treatment exist assessment predictive extremely comparison sizes increased
Topic 34: problem algorithm graph algorithms problems graphs optimal complexity method solution efficient log bound metric best
Topic 35: finite mathbb result points prove conditions second degree group point defined free classical structure zero

['magnetic phase spin states range temperature orders coupling strong weak critical length transition mode nearest',
 'support needed established protocol years path challenges internet issue plays multiplex lce secure exploits codeword',
 'model models order distribution density parameters proposed process noise error compared standard mean probability rate',
 'able frames flow games motion action potentially robot sensor shape environment robots super parallel environments',
 'quantum frequency spectrum response experimentally measurement account experiment frequencies exciton freedom pulse damping appropriate phonon',
 'study field systems large different dimensional properties energy small obtained interactions observed including type like',
 'control range contrast stability evolutionary perspective principles pair drift takes vehicle kinetic theoretic intrinsic utility',
 'approximation samples bayesian inference setting estimation kernel convergence guarantees signals negative sensing inverse semi variational',
 'simple force background physical need discussed kind moving transmission shell anomalous security relationship majority solid',
 'information level multi code stochastic language better strategy examples key optimization paths search open furthermore',
 'theory operators omega chain existence algebra algebras described factor gives evolution characterize formulate lie integral',
 'discuss variety loop fluid forcing understood tools emitter utilized author induces culture passivity freely magnetized',
 'matrix set estimates bounds convex coefficients special property geometric polynomial asymptotic volume geometry relative norm',
 'performance data classification source domain training image improve art machine input dataset generative target accuracy',
 'high state present low demonstrate experiments single techniques times end effective significant recently way finally',
 'evidence neutron sufficiently acceleration disks produced conclusion vertical substantial blue metal electric sites principal spirals',
 'results paper method methods new non use work space number provide function given linear case',
 'exchange vanishing absence excitations vortex responsible crossed antiferromagnet antiferromagnetic doping afm plumbene neighbor magnetization nontrivial',
 'mathcal general equation interesting equivalent employing position polynomials asymptotically price formed scalar taken complement verified',
 'learning approach based propose neural framework deep novel knowledge existing feature approaches learn prediction representation',
 'network networks random real complex datasets proposed nodes sampling community measures node measure focus true',
 'solar planets self place stable disk conflict unified planet hot ones concerned giant rise polarized',
 'communities propagation technique relevant artificial face estimating rates virtual normal researchers increasingly metrics schemes risk',
 'surface discrete channel equations matrices fixed partial covariance quaternion weighted estimators invariant difference estimator imaging',
 'experimental social lattice question understanding dynamics define delta analytical varying cross individuals connection groups perfect',
 'mass formation cluster line star matter lambda galaxy sigma galaxies dark light emission sim gravitational',
 'data time based applications features power detection multiple resolution series measurements available provides observations processing',
 'software requirements unique modern contract meet extends lipschitz old regularity exponent specifications contracts networking engineers',
 'example operator elements tau classes compact general regular notion consequence element closed necessary preferences introducing',
 'thermal plane magnitude ray pressure combined conventional electronic bulk plasma observational overall material atoms theoretically',
 'terms particular common positive selection transform protocols constructed euclidean fourier build symplectic sphere arise structures',
 'design convolutional loss manifolds string capacity explicitly improves outliers avoiding switch start contains implement cup',
 'analysis scale test research user identify context specific events users content management increase items consists',
 'global term simulated considering multidimensional relation bifacial treatment exist assessment predictive extremely comparison sizes increased',
 'problem algorithm graph algorithms problems graphs optimal complexity method solution efficient log bound metric best',
 'finite mathbb result points prove conditions second degree group point defined free classical structure zero']

In [ ]:
fig = best_model.visualize_topic_hierarchy()
fig.show()

In [36]:
topic_ids, topic_words = extract_top_words_from_fastopic(best_model, top_n=10)
print(topic_words)
df_topics = pd.DataFrame({
    "topic_id": topic_ids,
    "top_words": ["".join(ws) for ws in topic_words]
})
display(df_topics.head(40))

Topic 0: magnetic phase spin states range temperature orders coupling strong weak critical length transition mode nearest
Topic 1: support needed established protocol years path challenges internet issue plays multiplex lce secure exploits codeword
Topic 2: model models order distribution density parameters proposed process noise error compared standard mean probability rate
Topic 3: able frames flow games motion action potentially robot sensor shape environment robots super parallel environments
Topic 4: quantum frequency spectrum response experimentally measurement account experiment frequencies exciton freedom pulse damping appropriate phonon
Topic 5: study field systems large different dimensional properties energy small obtained interactions observed including type like
Topic 6: control range contrast stability evolutionary perspective principles pair drift takes vehicle kinetic theoretic intrinsic utility
Topic 7: approximation samples bayesian inference setting estimation kernel convergence guarantees signals negative sensing inverse semi variational
Topic 8: simple force background physical need discussed kind moving transmission shell anomalous security relationship majority solid
Topic 9: information level multi code stochastic language better strategy examples key optimization paths search open furthermore
Topic 10: theory operators omega chain existence algebra algebras described factor gives evolution characterize formulate lie integral
Topic 11: discuss variety loop fluid forcing understood tools emitter utilized author induces culture passivity freely magnetized
Topic 12: matrix set estimates bounds convex coefficients special property geometric polynomial asymptotic volume geometry relative norm
Topic 13: performance data classification source domain training image improve art machine input dataset generative target accuracy
Topic 14: high state present low demonstrate experiments single techniques times end effective significant recently way finally
Topic 15: evidence neutron sufficiently acceleration disks produced conclusion vertical substantial blue metal electric sites principal spirals
Topic 16: results paper method methods new non use work space number provide function given linear case
Topic 17: exchange vanishing absence excitations vortex responsible crossed antiferromagnet antiferromagnetic doping afm plumbene neighbor magnetization nontrivial
Topic 18: mathcal general equation interesting equivalent employing position polynomials asymptotically price formed scalar taken complement verified
Topic 19: learning approach based propose neural framework deep novel knowledge existing feature approaches learn prediction representation
Topic 20: network networks random real complex datasets proposed nodes sampling community measures node measure focus true
Topic 21: solar planets self place stable disk conflict unified planet hot ones concerned giant rise polarized
Topic 22: communities propagation technique relevant artificial face estimating rates virtual normal researchers increasingly metrics schemes risk
Topic 23: surface discrete channel equations matrices fixed partial covariance quaternion weighted estimators invariant difference estimator imaging
Topic 24: experimental social lattice question understanding dynamics define delta analytical varying cross individuals connection groups perfect
Topic 25: mass formation cluster line star matter lambda galaxy sigma galaxies dark light emission sim gravitational
Topic 26: data time based applications features power detection multiple resolution series measurements available provides observations processing
Topic 27: software requirements unique modern contract meet extends lipschitz old regularity exponent specifications contracts networking engineers
Topic 28: example operator elements tau classes compact general regular notion consequence element closed necessary preferences introducing
Topic 29: thermal plane magnitude ray pressure combined conventional electronic bulk plasma observational overall material atoms theoretically
Topic 30: terms particular common positive selection transform protocols constructed euclidean fourier build symplectic sphere arise structures
Topic 31: design convolutional loss manifolds string capacity explicitly improves outliers avoiding switch start contains implement cup
Topic 32: analysis scale test research user identify context specific events users content management increase items consists
Topic 33: global term simulated considering multidimensional relation bifacial treatment exist assessment predictive extremely comparison sizes increased
Topic 34: problem algorithm graph algorithms problems graphs optimal complexity method solution efficient log bound metric best
Topic 35: finite mathbb result points prove conditions second degree group point defined free classical structure zero
[['m', 'a', 'g', 'n', 'e', 't', 'i', 'c', ' ', 'p'], ['s', 'u', 'p', 'p', 'o', 'r', 't', ' ', 'n', 'e'], ['m', 'o', 'd', 'e', 'l', ' ', 'm', 'o', 'd', 'e'], ['a', 'b', 'l', 'e', ' ', 'f', 'r', 'a', 'm', 'e'], ['q', 'u', 'a', 'n', 't', 'u', 'm', ' ', 'f', 'r'], ['s', 't', 'u', 'd', 'y', ' ', 'f', 'i', 'e', 'l'], ['c', 'o', 'n', 't', 'r', 'o', 'l', ' ', 'r', 'a'], ['a', 'p', 'p', 'r', 'o', 'x', 'i', 'm', 'a', 't'], ['s', 'i', 'm', 'p', 'l', 'e', ' ', 'f', 'o', 'r'], ['i', 'n', 'f', 'o', 'r', 'm', 'a', 't', 'i', 'o'], ['t', 'h', 'e', 'o', 'r', 'y', ' ', 'o', 'p', 'e'], ['d', 'i', 's', 'c', 'u', 's', 's', ' ', 'v', 'a'], ['m', 'a', 't', 'r', 'i', 'x', ' ', 's', 'e', 't'], ['p', 'e', 'r', 'f', 'o', 'r', 'm', 'a', 'n', 'c'], ['h', 'i', 'g', 'h', ' ', 's', 't', 'a', 't', 'e'], ['e', 'v', 'i', 'd', 'e', 'n', 'c', 'e', ' ', 'n'], ['r', 'e', 's', 'u', 'l', 't', 's', ' ', 'p', 'a'], ['e', 'x', 'c', 'h', 'a', 'n', 'g', 'e', ' ', 'v'], ['m', 'a', 't', 'h', 'c', 'a', 'l', ' ', 'g', 'e'], ['l', 'e', 'a', 'r', 'n', 'i', 'n', 'g', ' ', 'a'], ['n', 'e', 't', 'w', 'o', 'r', 'k', ' ', 'n', 'e'], ['s', 'o', 'l', 'a', 'r', ' ', 'p', 'l', 'a', 'n'], ['c', 'o', 'm', 'm', 'u', 'n', 'i', 't', 'i', 'e'], ['s', 'u', 'r', 'f', 'a', 'c', 'e', ' ', 'd', 'i'], ['e', 'x', 'p', 'e', 'r', 'i', 'm', 'e', 'n', 't'], ['m', 'a', 's', 's', ' ', 'f', 'o', 'r', 'm', 'a'], ['d', 'a', 't', 'a', ' ', 't', 'i', 'm', 'e', ' '], ['s', 'o', 'f', 't', 'w', 'a', 'r', 'e', ' ', 'r'], ['e', 'x', 'a', 'm', 'p', 'l', 'e', ' ', 'o', 'p'], ['t', 'h', 'e', 'r', 'm', 'a', 'l', ' ', 'p', 'l'], ['t', 'e', 'r', 'm', 's', ' ', 'p', 'a', 'r', 't'], ['d', 'e', 's', 'i', 'g', 'n', ' ', 'c', 'o', 'n'], ['a', 'n', 'a', 'l', 'y', 's', 'i', 's', ' ', 's'], ['g', 'l', 'o', 'b', 'a', 'l', ' ', 't', 'e', 'r'], ['p', 'r', 'o', 'b', 'l', 'e', 'm', ' ', 'a', 'l'], ['f', 'i', 'n', 'i', 't', 'e', ' ', 'm', 'a', 't']]

    topic_id   top_words
0          0  magnetic p
1          1  support ne
2          2  model mode
3          3  able frame
4          4  quantum fr
5          5  study fiel
6          6  control ra
7          7  approximat
8          8  simple for
9          9  informatio
10        10  theory ope
11        11  discuss va
12        12  matrix set
13        13  performanc
14        14  high state
15        15  evidence n
16        16  results pa
17        17  exchange v
18        18  mathcal ge
19        19  learning a
20        20  network ne
21        21  solar plan
22        22  communitie
23        23  surface di
24        24  experiment
25        25  mass forma
26        26  data time
27        27  software r
28        28  example op
29        29  thermal pl
30        30  terms part
31        31  design con
32        32  analysis s
33        33  global ter
34        34  problem al
35        35  finite mat

In [25]:
best_model.visualize_topic(top_n=8)

In [39]:
# Fix 100% robusto para tus top words
def reconstruct_words_from_char_lists(topic_token_list):
    words = []
    for token_list in topic_token_list:
        # unir caracteres
        joined = "".join(token_list).strip()
        # dividir si hay espacios dentro
        for w in joined.split(" "):
            w = w.strip()
            if len(w) > 2:
                words.append(w)
    return words

# reconstruir todos los tópicos
fixed_topics = [reconstruct_words_from_char_lists(topic) for topic in topic_words]
print(fixed_topics)

# WordCloud
from wordcloud import WordCloud
import matplotlib.pyplot as plt

for tid, words in enumerate(fixed_topics):
    if not words:
        print("Topic vacío:", tid)
        continue

    text = " ".join(words)
    wc = WordCloud(width=1000, height=400, background_color="white", collocations=False).generate(text)

    plt.figure(figsize=(10,4))
    plt.imshow(wc, interpolation="bilinear")
    plt.title(f"Topic {tid}")
    plt.axis("off")
    plt.show()

[[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
Topic vacío: 0
Topic vacío: 1
Topic vacío: 2
Topic vacío: 3
Topic vacío: 4
Topic vacío: 5
Topic vacío: 6
Topic vacío: 7
Topic vacío: 8
Topic vacío: 9
Topic vacío: 10
Topic vacío: 11
Topic vacío: 12
Topic vacío: 13
Topic vacío: 14
Topic vacío: 15
Topic vacío: 16
Topic vacío: 17
Topic vacío: 18
Topic vacío: 19
Topic vacío: 20
Topic vacío: 21
Topic vacío: 22
Topic vacío: 23
Topic vacío: 24
Topic vacío: 25
Topic vacío: 26
Topic vacío: 27
Topic vacío: 28
Topic vacío: 29
Topic vacío: 30
Topic vacío: 31
Topic vacío: 32
Topic vacío: 33
Topic vacío: 34
Topic vacío: 35